### ISSUE TITLE
It looks like you support Unix domain sockets

### ISSUE THREAD

**Issue by michaellenaghan** [mysql-otp/mysql-otp#114]
Not a bug, a feature! 

Please forgive the Elixir dialect, but in 1.3.1, which is what's [currently on Hex](https://hex.pm/packages/mysql), it's possible to use a Unix domain socket by doing this:

```
iex(2)> {:ok, pid} = :mysql.start_link([
...(2)>   host: {:local, "/opt/local/var/run/mysql56/mysqld.sock" |> to_charlist},
...(2)>   port: 0,
...(2)>   database: "some_db" |> to_charlist, 
...(2)>   user: "some_user" |> to_charlist, 
...(2)>   password: "some_password" |> to_charlist
...(2)> ])
{:ok, #PID<0.1089.0>}
```

Worth mentioning somewhere? (Apologies if this is obvious to an old Erlang hand; it wasn't to this very new Elixir one!)

PS Possible to update Hex?

**Comment by michaellenaghan** [comment]
To keep this working I think the [unreleased change to the `host` spec](https://github.com/mysql-otp/mysql-otp/blob/master/src/mysql.erl#L126) will have to change again:

```
    {host, inet:socket_address() | inet:hostname()} | {port, integer()} |
```

Maybe something like this?

```
    {host, inet:socket_address() | inet:hostname() | {local, inet:local_address()}} | {port, integer()} |
```

 (Untested.)

**Comment by zuiderkwast** [comment]
Oh, that's great news! I didn't know! :-) I think unix domain socket was added to OTP in one of the recent versions, so it might just have started working out of nowhere.

We should have at least one test case connecting to local host using the unix domain socket. And fix the spec as mentioned.

Btw, I don't think you need to do `to_charlist`. For the local socket I'm not sure, but for user, password and database, a binary string should work fine.

**Comment by juhlig** [comment]
> Oh, that's great news! I didn't know! :-) I think unix domain socket was added to OTP in one of the recent versions, so it might just have started working out of nowhere.

Yup, it was introduced in experimental state in OTP 19.0, if I'm not mistaken. Don't know when it went to official state.

> We should have at least one test case connecting to local host using the unix domain socket. And fix the spec as mentioned.

No, this is not necessary. The type [`inet:socket_address()`](http://erlang.org/doc/man/inet.html#type-socket_address) includes [`local_address()`](http://erlang.org/doc/man/inet.html#type-local_address) in OTP versions that do support it. This is very convenient, since that way our spec is automatically, implicitly correct, no matter what OTP version `mysql-otp` is used with.

**Comment by zuiderkwast** [comment]
OK, the spec is complete, but we could add a test case or change one of the existing test cases, right? It should be setup to only run on OTP >= 19 in Travis. We should probably also mention somewhere that it's supported, in the README or in the docs.

**Comment by juhlig** [comment]
Sure, I can create a test for that (nothing fancy, just see if it connects, and maybe a simple query for good measure), but TBH I have not much of an idea how to set things up in travis ;) And what about running tests in a local environment, where we don't know the OTP version? Ie, how do we decide when to skip the test?

One thing worth mentioning (or handling internally) is the port setting. If it is not given in the connect options, it defaults to 3306, but for a local socket it must be 0.

**Comment by zuiderkwast** [comment]
Oh, then we should probably add some handling so we set port to 0 automatically if it's a local socket!

The condition for skipping the test case can be inside the test case itself. Look at the test case for JSON which depends on the MySQL version: https://github.com/mysql-otp/mysql-otp/blob/master/test/mysql_tests.erl#L620

**Comment by juhlig** [comment]
Ah, great, `system_info` is just what I was looking for. Didn't know that existed, learned something handy today :)

I'll get to this next week then, I guess :) Have a nice weekend.

**Comment by zuiderkwast** [comment]
You too!
