### ISSUE TITLE
Possible performance tweaks?

### ISSUE THREAD

**Issue by michaellenaghan** [mysql-otp/mysql-otp#119]
Here's what the erlang docs [say](http://erlang.org/doc/man/inet.html#setopts-2) about the `buffer` socket option:

> For TCP it is recommended to have val(buffer) >= val(recbuf) to avoid performance issues because of unnecessary copying. ... val(buffer) is automatically set to the above maximum when recbuf is set. However, as the size set for recbuf usually become larger, you are encouraged to use getopts/2 to analyze the behavior of your operating system.
> 
> Note that this is also the maximum amount of data that can be received from a single recv call. If you are using higher than normal MTU consider setting buffer higher.

On my machine here's what I get by default:

```
iex(8)> :inet.getopts(elem(:sys.get_state(conn), 3), [:buffer])
{:ok, [buffer: 1460]}                                                           
iex(9)> :inet.getopts(elem(:sys.get_state(conn), 3), [:recbuf])     
{:ok, [recbuf: 8192]}
iex(10)> :inet.getopts(elem(:sys.get_state(conn), 3), [:sndbuf])            
{:ok, [sndbuf: 8192]}
```

If I'm reading the docs right the default `buffer` size should be larger?

The reason I'm raising this as an issue is that, as far as I can tell, and as you can see above, I have to break encapsulation in order to do this myself.

Thoughts?

Another possible optimization is to set `nodelay` to `true`; the default is `false`:

```
iex(11)> :inet.getopts(elem(:sys.get_state(conn), 3), [:nodelay])
{:ok, [nodelay: false]}
```

Here's the description:

> If `Boolean == true`, option `TCP_NODELAY` is turned on for the socket, which means that also small amounts of data are sent immediately.

Since `mysql-otp` only sends complete messages I'm not sure delaying makes sense.

**Comment by michaellenaghan** [comment]
[Here](https://github.com/elixir-ecto/myxql/blob/master/lib/myxql/client.ex#L204) is what `myxql` does:

```
    buffer? = Keyword.has_key?(socket_options, :buffer)

    case :gen_tcp.connect(address, port, socket_options, connect_timeout) do
      {:ok, sock} when buffer? ->
        {:ok, sock}

      {:ok, sock} ->
        {:ok, [sndbuf: sndbuf, recbuf: recbuf, buffer: buffer]} =
          :inet.getopts(sock, [:sndbuf, :recbuf, :buffer])

        buffer = buffer |> max(sndbuf) |> max(recbuf)
        :ok = :inet.setopts(sock, buffer: buffer)
        {:ok, sock}

        ...
```

If a `buffer` socket option is given it's used. Otherwise `buffer` is set to the maximum of `buffer`, `recbuf ` and `sndbuf`.

**Comment by michaellenaghan** [comment]
In `start_link` the [`spec` for `Option`](https://github.com/mysql-otp/mysql-otp/blob/master/src/mysql.erl#L127) is missing `tcp_options` (which is documented [just above](https://github.com/mysql-otp/mysql-otp/blob/master/src/mysql.erl#L120)).

**Comment by zuiderkwast** [comment]
I think both suggestions are good!

I'll have a look at #125 now.

I have read up about TCP_NODELAY and Nagle's Algorithm and yes, I think we should use nodelay by default.

**Comment by michaellenaghan** [comment]
> I have read up about TCP_NODELAY and Nagle's Algorithm and yes, I think we should use nodelay by default.

OK, I'll do that in a separate pull request once the first is in. That seems cleaner, but if you don't care I can tack it onto the current one.

**Comment by zuiderkwast** [comment]
Re-opening the issue for the nodelay suggestion.

> OK, I'll do that in a separate pull request once the first is in.

Great, I'm waiting. :-)
