### ISSUE TITLE
Published docs are outdated

### ISSUE THREAD

**Issue by michaellenaghan** [mysql-otp/mysql-otp#120]
The docs published [here](https://mysql-otp.github.io/mysql-otp/) appear to be out of date. For example they're missing the docs for `change_user` and `stop` as well as any mention of the new `FilterMap` arg in `query`. (I know some of those things are very new.)

**Comment by michaellenaghan** [comment]
Also, the `ssl` option seems to be missing from the [table](https://github.com/mysql-otp/mysql-otp/blob/f43adad8e0a50c8f8120c407ec820d35add2f219/src/mysql.erl#L68) and from the corresponding [spec](https://github.com/mysql-otp/mysql-otp/blob/f43adad8e0a50c8f8120c407ec820d35add2f219/src/mysql.erl#L125).

**Comment by zuiderkwast** [comment]
Yeah, I agree, they seem to be out of date. The docs are generated using erlang.mk, I posted the docs using rebar3 but the hex package was uploaded using mix... I'll look into it one night soon.

**Comment by zuiderkwast** [comment]
Solved long ago.
