### ISSUE TITLE
Consider changing the default character set to utf8mb4

### ISSUE THREAD

**Issue by michaellenaghan** [mysql-otp/mysql-otp#121]
Please consider changing the default character set [here](https://github.com/mysql-otp/mysql-otp/blob/f43adad8e0a50c8f8120c407ec820d35add2f219/include/protocol.hrl#L25):

```
-define(UTF8, 16#21). %% utf8_general_ci
```

to:

```
-define(UTF8, 16#2d). %% utf8mb4_general_ci
```

Otherwise characters off the basic multilingual plane (e.g., emoticons and many Asian characters) will, depending on the SQL mode, either silently be discarded or error:

```
>  :mysql.query(conn, "CREATE TABLE t (i INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, c CHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci);")
:ok

>  :mysql.query(conn, "select @@character_set_results, @@character_set_client, @@character_set_connection;")
{:ok, 
  ["@@character_set_results", "@@character_set_client", "@@character_set_connection"], 
  [["utf8", "utf8", "utf8"]]}

> :mysql.query(conn, "set session sql_mode = '';")  
:ok

> :mysql.query(conn, "insert into t (c) values (?);", ["!!!😃!!!"])           
11:41:25.669 [warn]  Warning 1366: Incorrect string value: '\xF0\x9F\x98\x83!!...' for column 'c' at row 1
 in insert into t (c) values (?);

:ok

> :mysql.query(conn, "select * from t where i = ?;", [:mysql.insert_id(conn)])
{:ok, ["i", "c"], [[1, "!!!????!!!"]]}

> :mysql.query(conn, "set session sql_mode = 'TRADITIONAL';")            
:ok  

> :mysql.query(conn, "insert into t (c) values (?);", ["!!!😃!!!"])      
{:error,
 {1366, "HY000",
  "Incorrect string value: '\\xF0\\x9F\\x98\\x83??...' for column 'c' at row 1"}}
```

Here's what that sequence looks like after making the change:

```
>  :mysql.query(conn, "select @@character_set_results, @@character_set_client, @@character_set_connection;")
{:ok, 
  ["@@character_set_results", "@@character_set_client", "@@character_set_connection"], 
  [["utf8mb4", "utf8mb4", "utf8mb4"]]}

> :mysql.query(conn, "insert into t (c) values (?);", ["!!!😃!!!"])           
:ok

> :mysql.query(conn, "select * from t where i = ?;", [:mysql.insert_id(conn)])
{:ok, ["i", "c"], [[1, "!!!😃!!!"]]}
```

(The SQL mode no longer matters since there's no longer a problem.)

In the meantime a workaround (or an alternative approach if you don't think `utf8mb4` should be the default) is to add this to the list of `connect` queries:

    "SET NAMES utf8mb4;"

**Comment by zuiderkwast** [comment]
I think it's a good suggestion.

> (The SQL mode no longer matters since there's no longer a problem.)

In some earlier versions of MySQL there was a problem with characters requiring 4 bytes in UTF-8 beacause of some assumptions that e.g. VARCHAR(10) never needs more than 30 bytes. If I remember correctly, this is why utf8mb4 was introduced. Are you saying this doesn't matter? From which version is this no longer a problem? We support MySQL 4.1....

The character set is set in the handshake response, so we can use the MySQL version number (which we already have at this point) if there is no other way to tell if the server can handle it.

**Comment by michaellenaghan** [comment]
Just so we're clear: my understanding of MySQL is improving, but I'm no expert. With that out of the way, here's my answer.

What we're talking about here is the character set the server assumes the client is using. That's it—and that's separate from the character set the server itself is using in, say, a particular column.

With this change in place, here are some scenarios:

 * The client tries to insert an emoji into a `latin1` column. Depending on the SQL mode the server would *still* either drop the character or error.

 * The client tries to insert an emoji into a `utf8` column. Depending on the SQL mode the server would *still* either drop the character or error.

 * The client tries to insert an emoji into a `utf8mb4` column. The attempt would succeed.

In other words, this change would allow success but not prevent failure. (Right now the third scenario would fail when you'd actually expect success.)

The point you're making is correct: in MySQL a `utf8` character set requires up to 3 bytes per character, and a `utf8mb4` character requires up to 4 bytes per character. (To be clear: MySQL is the only product I know of anywhere that makes that distinction. When everyone else talks about UTF8 they're talking about what MySQL calls `utf8mb4`.) But the character set of a column is a decision made when you create the column; this change wouldn't affect that decision.

To put that another way, this change would affect the values of `character_set_client`, `character_set_connection`, and `character_set_results`—but not `character_set_server`, `collation_server`,  `character_set_database`, or `collation_database`. The last four are the defaults that affect table columns.

Here, I think, are the key pages to read:

 * [10.4 Connection Character Sets and Collations](https://dev.mysql.com/doc/refman/5.7/en/charset-connection.html)
 * [10.3.2 Server Character Set and Collation](https://dev.mysql.com/doc/refman/5.7/en/charset-server.html)
 * [10.3.3 Database Character Set and Collation](https://dev.mysql.com/doc/refman/5.7/en/charset-database.html)

The first link above talks about error handling. Basically, if the server doesn't support the requested character set it will silently fall back to its own default. That's not good. I was able to track down [this](https://mysqlserverteam.com/mysql-8-0-when-to-use-utf8mb3-over-utf8mb4/):

> * MySQL 4.1 (2004) was the first version to support character sets and collations.  The default character set was latin1, but utf8[mb3] was available as an option.  An optimization was chosen to limit utf8 to 3 bytes, enough to handle almost all modern languages. 
>
> * MySQL 5.5 (2010) added support for up to 4 byte utf8 using the new utf8mb4 character set.

So, yes, it looks like you should special case versions before 5.5 to `utf8` rather than `utf8mb4`.

**Comment by michaellenaghan** [comment]
By the way, my suggestion uses `utf8mb4_general_ci` because I knew it would be supported in all versions that support `utf8mb4`. But that's actually a terrible collation to use. `utf8mb4_unicode_ci` would be better, `utf8mb4_unicode_520_ci` would be better still, and `utf8mb4_0900_ai_ci` would be best. The problem is that they wouldn't necessarily be supported.

Having said that, I think client collation only affects literal strings. For anything column-related the column's collation would take precedent. So: `utf8mb4_general_ci` is *probably* good enough; it just isn't ideal.

If it isn't good enough, users can still fine tune by using `SET NAMES`—e.g., `SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;`.

**Comment by zuiderkwast** [comment]
I agree with what you're saying.

> So, yes, it looks like you should special case versions before 5.5 to utf8 rather than utf8mb4.

Good finding! Let's do this!

As for the collation of the connection, I agree it's not very important, because the collation specified in `CREATE TABLE` has higher precedence as you say. That's my interpretation too. Let's go for the one guaranteed to exist.

I'll accept a PR with this.

Ideally, we could test it for two different MySQL versions if we do it the way it's done in `mysql_protocol_tests` using mocked socket, but it might be too much work. There's not even a handshake test case done in that way yet. Running travis for multiple mysql versions is another bullet on my wishlist...

**Comment by michaellenaghan** [comment]
I'm new to Elixir and don't really know Erlang, but if that doesn't bother you I'll give it a shot. :-)

Let me think a bit about the conditional check.

**Comment by zuiderkwast** [comment]
Awesome! You do know Erlang. :-)
