### ISSUE TITLE
2.0 Roadmap proposal

### ISSUE THREAD

**Issue by juhlig** [mysql-otp/mysql-otp#124]
I have been thinking about what improvements could be made to `mysql-otp` in the future, which I'm putting up for discussion here. As the things I came up with introduce some breaking changes, I suggest this as a road map draft for a new major version.

# API
* get rid of the overloaded functions where the behavior depends on argument type (`like `query/3`, where the third parameter could be a list of params, a timeout, or a filter/map function) in favor of multiple functions with clear meanings, and move some of the extra args into option arguments
* allow maps for options; the proplists we have now can stay as an alternative, but the focus should be on the more modern maps (this restricts backwards compatibility to OTP>=17)

# Connection process
* a state machine may be a better fit than a gen_server; with `gen_fsm` being deprecated, this means `gen_statem` (this restricts backwards compatibility to OTP>19.3 (or whatever that 19.X it was where the callback mode selection was moved from `init` to `callback_mode/0`))
* move the execution of post-connect queries and prepares inside the connection process
* move gen_server (or gen_statem) calls into functions in the connection process module, and call those from the API module; this is some minor cosmetics, I just think the API module doesn't have to know what the connection process actually is
* provide manual/on-demand connecting, as I already outlined in #122. Especially this is where a state machine would be a better fit than a `gen_server`

# Protocol
* provide MySQL 8 compatibility

# Tests
* as I'm currently digging into `PropEr`, I think some `eunit` tests may be replaced by property tests, and new ones added, for more thorough testing (this introduces another test dependency)

# Docs
* remove the documentation that is not relevant for the code itself but more of a user guide; put that up in a separately maintained user guide (personally, I prefer `asciidoc` for this, but it introduces some new dependencies: `asciideck` as a doc dependency, and `a2x`, `dblatex` and `xsltproc` installed in the OS to compile it)

<hr />

As for the changes that require a newer OTP version (17 or even 19), my view on this is that
* new projects that will make use of `mysql-otp` will most likely be implemented on a recent OTP version, certainly not something like R16
* older projects that use it on old OTP versions can still do so by using an older release of `mysql-otp` where it is supported

**Comment by zuiderkwast** [comment]
I want MySQL 8 to be solved in version 1. There's a PR which seems to be working but tests are missing. What I'd like to prioritize is running the tests on multiple MySQL and MairaDB versions in Travis so it would be easier to test this.

If you can make use of PropEr, sure, go for it! We have had some cases with encoding numbers in the past which could have been found using property based testing. I think manual testing with proper to find corner cases and bugs, then writing these as eunit tests is a good way too.

The API with overloaded functions, I don't think it is a major problem. Do you? As for maps in the options, same. Neither of these are strong enough reasons to break backward compatibility IMO.

I'm fine with requiring OTP 19.3. This is already quite some years old. But it's a lot of work to refactor it to gen_statem; is it really worth it? We could just save the connection state in the `#state{}`. That's what the gen_statem does internally anyway, isn't it?

As for the other things, I don't see why we need to step the major version. It can be done in the current version.

**Comment by michaellenaghan** [comment]
I'm still learning about Elixir, Erlang, OTP, mysql-otp, etc., so consider this suggestion in that light.

My current understanding is that mysql-otp runs entirely in a separate `gen_server` process; query results are copied across process boundaries. My further understanding is that some things are optimized for cross-process copying and some things are not. I know that binaries are; I don't know if large data structures are (or are under certain conditions).

I can think of two other approaches that might yield better performance.

The first, which is a little more conservative, would be to keep `gen_tcp` in a separate process, but just use it for sending and receiving. With that approach, only binaries would be copied from one process to another; encoding and decoding would happen in the "client" process.

The second, which is more aggressive, would be to keep state (e.g., the socket) in a separate process, and perform all work in the "client" process.

I think the current implementation, which uses `{active, once}`, would require the first approach.

No doubt that all sounds a little insane, or at least unusual, but I think it's roughly the direction Elixir/Ecto went in [DBConnection](https://hexdocs.pm/db_connection/DBConnection.html). If it's of interest I could try to think of a way to model the core idea in a benchmark of some kind to see if it would actually be worthwhile?

On a somewhat related point, personally I'd love to try to eliminate the use of `{active, once}`. As I said, I'm still in the process of learning, but I'm not convinced it's actually required—and I think it makes the implementation more complicated. That change could be made even if the process architecture was kept as is.

**Comment by zuiderkwast** [comment]
I think Erlang users are more conservative than Elixir users in general. :-)

>  If it's of interest I could try to think of a way to model the core idea in a benchmark of some kind to see if it would actually be worthwhile?

Yes, definitely! Just comparing the different clients would be interesting. Here's a comparison for inspiration: https://tjheeta.github.io/2015/05/31/elixir-and-erlang-mysql-drivers/

As for `{active, once}`, it was added to be able to detect that the server goes down. I don't know how you'd detect that otherwise.

**Comment by michaellenaghan** [comment]
Benchmarking would be good and useful in its own right, but what I meant was different: create an artificial benchmark—no MySQL or mysql-otp at all—that in one case parses a binary and copies the result across processes to the client and in the other case copies the binary across processes and then parses in the client. The point would be to see if the difference was 0%, 10%, 100%, 1000%, etc.—i.e., is it worthwhile or not?—before actually tackling the change. But if it's not of interest, no worries, I know how unusual it sounds.

Could you point me at something that explains the `{active, once}` thing? I haven't run across that in anything I've read so far.

**Comment by zuiderkwast** [comment]
#33

**Comment by juhlig** [comment]
> I want MySQL 8 to be solved in version 1.

Fair enough ;)

> There's a PR which seems to be working but tests are missing.

That would be #101, but it has been closed because the PR branch was deleted.

> What I'd like to prioritize is running the tests on multiple MySQL and MairaDB versions in Travis so it would be easier to test this.

I have been toying around with it, but tl;dr: I gave up ;) There seems to be no really nice way to use MySQL8 with travis. The only thing I found was [this stackoverflow article](https://stackoverflow.com/questions/50237943/travis-how-to-run-tests-against-different-mysql-backends), but I couldn't make it work.

> If you can make use of PropEr, sure, go for it! We have had some cases with encoding numbers in the past which could have been found using property based testing. I think manual testing with proper to find corner cases and bugs, then writing these as eunit tests is a good way too.

Ok, I'll keep it in mind. I'm just starting with PropEr, so don't expect it soon, though.

> The API with overloaded functions, I don't think it is a major problem. Do you?

Not a problem as such, unless we ever get to a point where we have two arguments of the same type.

Remember when we made that filter/map feature? We found that edoc only considers the first of a multi-clause spec, so I put [this](https://bugs.erlang.org/browse/ERL-849) up at bugs.erlang. The response states that "rather than overloading a function, separate functions should be used for different argument types" (and yes, the older modules in OTP itself do that all the time). Anyway, that has been nagging me ever since, like "this is not how its supposed to be done (nowadays)".

> As for maps in the options, same. Neither of these are strong enough reasons to break backward compatibility IMO.

If you're fine with OTP 19, as you say below, maps just come along with it ;) In that case, no breaking change occurs, as we can accept both proplists and maps then.

> I'm fine with requiring OTP 19.3. This is already quite some years old. But it's a lot of work to refactor it to gen_statem; is it really worth it?

Actually, it's not that big a deal. I have done it a few times before. Much of it is just rewriting the `handle_*` callbacks. One big difference (that, as far as I can see, is rarely mentioned) is that the `From` given in synchronous calls does not contain the pid of the real caller any more, as it does with `gen_server` and old `gen_fsm`, but that of a proxy process. `mysql_conn` relies on it at a few places, but this can be mitigated.

So, the rewrite to `gen_statem` is the easy part ;) If it is _worth_ it, I'm not 100% sure, also what callback mode would be the best fit then. It's what I would chose if I had to implement it anew, with #122 already in mind. I'll look deeper into it all later.

> We could just save the connection state in the `#state{}`. That's what the gen_statem does internally anyway, isn't it?

I have no idea ;)

> As for the other things, I don't see why we need to step the major version. It can be done in the current version.

Ok, apart from the proposed API changes (separate functions instead of overloaded ones) and higher OTP version requirements that come with maps (>=17) and/or `gen_statem` (>=19.3), nothing of the proposals break anything, yes. So if we take out the part of the API proposal that would be breaking things, and if you are ok with raising the OTP version requirements, this all could be done now.

**Comment by zuiderkwast** [comment]
The recently-closed MySQL 8 PR is #102. It was closed just few days ago.

Testing MySQL 8 in Travis is done by mariaex and myxql I think. Let's talk about this here: #99.

Regarding EDoc and overloaded specs, I think it's a flaw of EDoc because Erlang supports overloaded specs, whether Richard likes it or not. But if we're moving away from EDoc anyway, this is a non-issue.

If we allow maps along with proplists and use gen_statem internally, sure the API is backward compatible, but it's still a backward-incompatible to drop support for some Erlang/OTP versions. Thus, I don't think we should do these things.

**Comment by juhlig** [comment]
> If we allow maps along with proplists and use gen_statem internally, sure the API is backward compatible, but it's still a backward-incompatible to drop support for some Erlang/OTP versions. Thus, I don't think we should do these things.

Ok, granted, those are all things that are not necessary, so yes, I agree we shouldn't do it ;)

**Comment by juhlig** [comment]
As most of the proposals in this issue have been either adressed or decided against, I suggest this issue can be closed. The suggestions from @michaellenaghan are still pending, but it looks like nothing will come of it for the time being.
