### ISSUE TITLE
LIKE operator

### ISSUE THREAD

**Issue by rajaasim** [mysql-otp/mysql-otp#132]
is there a way to execute a query with like operator?
something like

mysql:query(Pid, <<"SELECT * FROM users WHERE user_name LIKE '?%'">>, ["whatever"]).

**Comment by zuiderkwast** [comment]
Yes, just write `?` instead of `'?%'`.

**Comment by zuiderkwast** [comment]
Yes. Note that `?` is a placeholder for a complete value. I can not be used inside a string. If you need to add the '%' sign to the pattern using SQL, you can do something like `... WHERE user_name LIKE CONCAT(?, '%')`.

Another way is to do it on the Erlang side, i.e. `mysql:query("... user_name LIKE ?", ["whatever%"])`.

**Comment by zuiderkwast** [comment]
Closing this. Hope you're happy with the answer. Please re-open otherwise!
