### ISSUE TITLE
Connections via ProxySQL

### ISSUE THREAD

**Issue by guero235** [mysql-otp/mysql-otp#133]
Today i was setting up proxySQL to handle some connection pooling / SSL connections in a dev environment, however, i wasn't able to get a mysql connection. Yes, i know that mysql-otp does both pooling AND ssl however other infrastructure pieces require something like proxySQL.  Anyway..

I was getting this error:

```
{{badmatch,{error,{{badmatch,0},[{mysql_protocol,handshake_finish_or_switch_auth,5,[{file,"src/libs/mysql-otp/mysql_protocol.erl"},{line,87}]},{mysql_conn,init,1,[{file,"src/libs/mysql-otp/mysql_conn.erl"},{line,90}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}}},[{poolboy,new_worker,1,[{file,"src/libs/poolboy/poolboy.erl"},{line,300}]},{poolboy,prepopulate,3,[{file,"src/libs/poolboy/poolboy.erl"},{line,329}]},{poolboy,init,3,[{file,"src/libs/poolboy/poolboy.erl"},{line,168}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
```

Perhaps there is another config setting i'm missing? 

here is the config i was using:
```
[
			{host, ?MYSQL_HOST},
			{port, ?MYSQL_PORT},
			{user, ?MYSQL_USER},
			{password, ?MYSQL_PASSWORD},
			{database, ?MYSQL_DB},
			{keep_alive,true}
]
```

**Comment by zuiderkwast** [comment]
It seems that proxySQL returns something unexpected during handshake, so either this is a bug or proxySQL is misbehaving. The error trace says the error is on line 87 in mysql_protocol.erl, but that line is just a comment (https://github.com/mysql-otp/mysql-otp/blob/master/src/mysql_protocol.erl#L87). What version exactly are you using? Perhaps you can say what's on line 87?

The config looks fine, as long as those macros are strings or binaries.

**Comment by vkatsuba** [comment]
Hi All,

Any updates? I have the same issue with ProxySQL.

**Comment by zuiderkwast** [comment]
Hi @vkatsuba! Then perhaps you can say on which line you get this error and what is on that line? Or even debug it? I expect it has something to do with where we check the capability flags.

No one is paid to work on this project so any contributions are appreciated.

**Comment by vkatsuba** [comment]
@zuiderkwast, thanks for feedback. I not sure that the issue in the same line, please see error below:

```sh
[error] <0.471.0>@mysql_protocol:handshake_finish_or_switch_auth:76 CRASH REPORT Process <0.471.0> with 0 neighbours crashed with reason: no match of right hand value 0 in mysql_protocol:handshake_finish_or_switch_auth/5 line 76
```

**Comment by zuiderkwast** [comment]
Interesting. It is what i thought, more or less.

1. Client opens socket.
2. Server sends Handshake, with some status flags
3. Client sends Handshake Response
4. Server sends Handshake Confirm, with some status flags again

We check that the status flags sent the second time are the same as the status flags sent the first time. Here, the second time, the server sent status = 0 (i.e. no status flags set), which is probably incorrect. We are strict here so we crash. Probably we should not be so strict. We're not really using the flags for anything anyway.

If you delete this line, it will probably work.

**Comment by vkatsuba** [comment]
Hi @zuiderkwast, 

Many thanks for response,  this is very helpful, I will try investigate the reason - why the server side send handshake again.

Regards,
--V

**Comment by zuiderkwast** [comment]
PR #117 is related. ProxySQL is even mentioned in a comment. This PR was merged in April, after version 1.5.0 was tagged. Can you try that to see if that solves the problem?

I should probably tag a new version anyway. There have been some fixes since then.

**Comment by vkatsuba** [comment]
@zuiderkwast, good news, with master branch I don't have the error and all working as expected. ш I suppose this ticket can be closed.
Cheers!

**Comment by zuiderkwast** [comment]
Great! I'll tag a new version, hopefully soon.
