### ISSUE TITLE
Ability to do explicit begin, commit and rollback

### ISSUE THREAD

**Issue by jquadrin** [mysql-otp/mysql-otp#14]
Is this a possibility?

**Comment by zuiderkwast** [comment]
Yes, it is possible. Also, mysql:in_transaction/1 works as expected inside and outside transactions started with explicit query("BEGIN").

Just don't mix transaction/2 with query("BEGIN"), query("COMMIT"). If you do BEGIN inside a transaction started with transaction/2, the BEGIN query will result in an implicit commit in the outer transaction/2 which will cause the outer transaction/2 to raise an exception.
