### ISSUE TITLE
mysql.app is missing kernel from applications list

### ISSUE THREAD

**Issue by mihongkun** [mysql-otp/mysql-otp#144]
PS D:\ws\erlang\hope> .\0-start.bat
===> Verifying dependencies...
===> Fetching mysql (from {git,"https://github.com/mysql-otp/mysql-otp",{tag,"1.5.1"}})
===> Linking _build/default/lib/mysql to _build/prod/lib/mysql
===> Compiling mysql
===> "d:/ws/erlang/hope/_build/default/lib/mysql/ebin/mysql.app" is missing kernel from applications list
===> "d:/ws/erlang/hope/_build/default/lib/mysql/ebin/mysql.app" is missing stdlib from applications list
===> Compiling jsx
===> Compiling ranch
===> Compiling cowboy
===> Compiling hope
===> Starting relx build process ...
===> Resolving OTP Applications from directories:
          d:/ws/erlang/hope/_build/prod/lib
          d:/ws/erlang/hope/apps
          d:/dev/erlang/erl10.1/lib
          d:/ws/erlang/hope/_build/prod/rel
===> Resolved hope-0.1.0
===> Including Erts from d:/dev/erlang/erl10.1
===> release successfully created!

![image](https://user-images.githubusercontent.com/10411214/69032265-0acdb380-0a17-11ea-9ce5-7b179adbc06c.png)

**Comment by zuiderkwast** [comment]
Right, they should be added. I guess nobody used releases or perhaps everybody just ignored these warnings. I guess `ssl` should be added too.

**Comment by zuiderkwast** [comment]
Solved by #145
