### ISSUE TITLE
Add mysql-otp to erlang.mks index

### ISSUE THREAD

**Issue by juhlig** [mysql-otp/mysql-otp#146]
Funny thing is, I'm almost certain that it was in there before and that this was the way by which I got aware of this project in the first place.

**Comment by zuiderkwast** [comment]
Shouldn't this be an issue in the erlang.mk repo then?

**Comment by juhlig** [comment]
Not really, it works by making PRs to that repo, ie usually by the maintainers who wish their project to be listed in the index, and keeping it up to date (pushing new PRs to the index for new releases). I can do that, actually I just wanted to know if you wanted `mysql-otp` listed in the index, or not :)

**Comment by zuiderkwast** [comment]
Sure!

Then you should know that @essen wanted to add it some years ago but there is an outdated one with the same application name "mysql". See #19. The old one shouldn't be used by anyone IMO, but I'm not sure it's my decision to make....

**Comment by essen** [comment]
I'm fine replacing it now.

**Comment by juhlig** [comment]
@zuiderkwast @essen then I would add/replace `mysql.mk` with the following:
```text
PACKAGES += mysql
pkg_mysql_name = mysql
pkg_mysql_description = MySQL client library for Erlang/OTP
pkg_mysql_homepage = https://github.com/mysql-otp/mysql-otp
pkg_mysql_fetch = git
pkg_mysql_repo = https://github.com/mysql-otp/mysql-otp
pkg_mysql_commit = 1.5.1
```

Ok with you? (I took the description from `doc/overview.edoc`)

**Comment by zuiderkwast** [comment]
Looks good to me!

**Comment by juhlig** [comment]
https://github.com/ninenines/erlang.mk/pull/869

**Comment by essen** [comment]
This was merged. Thanks!

**Comment by zuiderkwast** [comment]
Great! I'm closing this then.
