### ISSUE TITLE
Prepending to TCP options list in connect_socket

### ISSUE THREAD

**Issue by juhlig** [mysql-otp/mysql-otp#147]
https://github.com/mysql-otp/mysql-otp/blob/08b6eabfe41e980613300092763335efb8c6fa09/src/mysql_conn.erl#L152-L154

Adding something to the socket options this way is "unsafe". If one of those options is present in `TcpOpts`, they will be used, as the last occurence in the list is the one that gets used by `gen_tcp:connect`. For `mode` (or the same via `binary` / `list`), `packet` and `active`, this will result in an error if it is not `binary`, `0` (or `raw`), and `false`, respectively, while for `nodelay` what is in `TcpOpts` just overrides `true`.

Not sure if this should be changed and to what behavior. After all, options that would make a connection unusable when invalid (`mode` not `binary`, `packet` not `0` or `raw`, `active` not `false`) _do_ result in an error, and with `nodelay` set to `false` the connection would still work. What do you think?

**Comment by zuiderkwast** [comment]
Allowing TcpOpts is good for anyone who knows what they're doing and need to tweak the connection. For those who actively try to mess things up, they can try to do so and then revert to the defaults when they realize it doesn't work, so I didn't put any effort in preventing this.

If you want, you can check that neither of `packet`, `active` nor `binary` is defined in TcpOpts and raise an `error(badarg)` if they are, in `start_link/1`. We can consider `nodelay` just as a default which can be overridden if anyone wants to do that.

Does this seem reasonable?

**Comment by juhlig** [comment]
Instead of going for some big checking gymnastics, we could just _append_ "our" parameters to the given TCP options list, instead of _prepending_. This should ensure they are what is used regardless of what the user gave, notwithstanding any changes in how OTP handles the options list, which I think is unlikely.

**Comment by zuiderkwast** [comment]
OK! Prepend nodelay and append the others then?

**Comment by juhlig** [comment]
Ah, good idea :) Will see to it tomorrow :)
