### ISSUE TITLE
Problems with single qoute in a binary.

### ISSUE THREAD

**Issue by RaoH** [mysql-otp/mysql-otp#15]
When encoding a binary that has a single quote in it, only the first instance of the single quote gets replaced by a double single quote.

Example
 <<"My name is 'joey'.">>
Result:
<<"My name is ''joey'.">>  (which will lead to an sql error).

Think the binary:replace is missing the global option in mysql_encode:encode/1 for the binary case.

**Comment by zuiderkwast** [comment]
Obviously that is the solution. There is another binary:replace in backslash_escape/1 that also needs `[global]`. The tests should be modified so that the strings contains more than one of these characters.
