### ISSUE TITLE
Transaction deadlock and retries in MySQL <5.7 and >=5.7

### ISSUE THREAD

**Issue by juhlig** [mysql-otp/mysql-otp#158]
As previously observed, the rollback behavior on transaction deadlocks differs between MySQL versions before and after 5.7. In versions <5.7, the `BEGIN` is _not_ rolled back and statements following the deadlock rollback are _inside_ a transaction, while in versions >=5.7 the `BEGIN` seems to be rolled back also, and subsequent statements are executed _outside_ of a transaction.

`mysql-otp` implements transaction retries by following the <5.7 behavior. This results in an implicit commit error when the first query of the transaction is being retried, which is a nuisance. More seriously, this causes said first query to always being executed, which is unexpected.

I think this should be addressed quickly?

**Comment by zuiderkwast** [comment]
I fixed it already! #156

**Comment by juhlig** [comment]
Oh, I missed that. Good work 😃

And Happy New Year 😊

**Comment by zuiderkwast** [comment]
Happy new year!
