### ISSUE TITLE
Support Stored Procedure.

### ISSUE THREAD

**Issue by aposto** [mysql-otp/mysql-otp#16]
The error message comes after the call stored procedure.
mysql_pool:query(pool_game, "CALL sp_get_user_info(?)", [UID]).
 {error,{1312,<<"0A000">>,
           <<"PROCEDURE gamedb.sp_get_user_info can't return a result set in the given context">>}}

**Comment by zuiderkwast** [comment]
Ok, good to know.

After a quick search, it appears that a stored procedure can return multiple sets of columns and rows. The solution appears to be setting the flag for CLIENT_MULTI_STATEMENTS or CLIENT_MULTI_RESULTS in the handshake.

The implementation seems to be strait forward, but this would require a small addition to the API for returning multiple result sets. Perhaps like this: `{ok, [{Columns1, Rows1}, {Columns2, Rows2}, ...]}`? But if there is only one result set, it should still be returned as `{ok, Columns, Rows}` I guess...

I hope I can look into this next week. If anyone else wants to do it, here's a pointer: https://dev.mysql.com/doc/internals/en/stored-procedures.html

**Comment by fabiomsouto** [comment]
Hello,

Bumped into the same issue. @zuiderkwast did you get a chance to have a look at this? Just to know if I should wait or just implement it and do a pull req.

**Comment by zuiderkwast** [comment]
I'm at it now.

**Comment by zuiderkwast** [comment]
Please test the branch **multi-statements**: https://github.com/mysql-otp/mysql-otp/tree/multi-statements. If it works for you, I will add documentation and merge it..

I have implemented multiple result sets (needed for calling stored procedures) which means that a single query can return multiple result sets and also multiple statements which means that multiple semicolon-separated queries can be done in the same call to query.

When a query (or execute) returns more than one result set, it is returned as `{ok, [{ColumnNames1, Rows1}, {ColumnNames2, Rows2}, ...]}`. For one result set and zero result sets it is like before.

**Comment by zuiderkwast** [comment]
This is now in master. Please test and re-open this issue if there are any problems!
