### ISSUE TITLE
Support connection pool?

### ISSUE THREAD

**Issue by wwhai** [mysql-otp/mysql-otp#167]
# Query operation can support process pool?Like JDBC thread pool.

**Comment by juhlig** [comment]
I _guess_ what you are looking for is something like [`mysql-otp-poolboy`](https://github.com/mysql-otp/mysql-otp-poolboy)?

Please state your questions more precisely/accurately/elaborate in the future ^^;;;

**Comment by wwhai** [comment]
> I _guess_ what you are looking for is something like [`mysql-otp-poolboy`](https://github.com/mysql-otp/mysql-otp-poolboy)?
> 
> There are also other pool implementations apart from [`poolboy`](https://github.com/devinus/poolboy/) out there, which you may want to look into. I have heard of people using `mysql-otp` with [`pooler`](https://github.com/seth/pooler), and it is probably usable with [`worker_pool`](https://github.com/inaka/worker_pool) (but I never tried). We have no handy adapters for those, though. I'm currently preparing one for [`hnc`](https://github.com/juhlig/hnc), but that will still take a few days at least.
> 
> Anyway, please state your questions more precisely/accurately/elaborate in the future ^^;;;

Ok,thanks for your anwser.
