### ISSUE TITLE
About Warning 1300: Invalid utf8mb4 character string: '836A'

### ISSUE THREAD

**Issue by vebeter** [mysql-otp/mysql-otp#177]
It will show the Warning about  utf8mb4, but table already set utf8mb4,
Is this a special problem?

Warning 1300: Invalid utf8mb4 character string: '836A' 
 in update daily_data set `data`='僯' where id=1;

%%Erlang work:
mnesia:insert(#daily_data{id=1,data=[]}).

sql is:    " insert into daily_data(`id`,`data`) values (1,'僯'); "

%% table 
DROP TABLE IF EXISTS `daily_data`;
CREATE TABLE `daily_data` (
  `id` bigint(20) unsigned NOT NULL COMMENT 'Key',
  `data` blob COMMENT 'Daily_data',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

**Comment by zuiderkwast** [comment]
I have never seen this, but a BLOB column doesn't care about charset. It stores the bytes you send to it and doesn't use character encodings.

I tried these CREATE TABLE, INSERT and then SELECT in the command line mysql client, but I didn't get a warning. Did you get the same warning in mysql command line client and from Erlang?

Did you try to use VARCHAR or TEXT instead of BLOB?

**Comment by vebeter** [comment]
Hi~ Thanks reply. 
I tried to  input "  insert into daily_data(id,data) values (1,'僯'); "  in  mysql command line client, it has no warning.
Only shows "Query OK, 1 row affected (0.00 sec)."



But,I called this function at my module :

Query=  " insert into daily_data(id,data) values (1,'僯'); ",
Pool = 'db_mysql_server_pool',
TimeOut = 60000,
handle_result(catch mysql_poolboy:query(Pool , Query, TimeOut )).

handle_result({ok, Cols, Rows}) ->
    {selected, Cols, Rows};
handle_result(ok) -> {updated, ok};
handle_result({error, {no_connection_in_pool, Pool}}) ->
    ?ERROR("mysql error:no_connection_in_pool ~p", [Pool]),
    {error, no_connection};
handle_result({error, Result}) when is_tuple(Result) ->
    {ErrCode, _State, Reason} = Result,
    ?ERROR("mysql error:~p", [Result]),
    {error, {ErrCode, Reason}};
handle_result({error, "message timed out"}) ->
    ?ERROR("mysql error:message timed out"),
    {error, timeout};
handle_result({'EXIT', {Reason, _}}) ->
    ?ERROR("mysql error:~w", [Reason]),
    {error, Reason};
handle_result(Res) ->
    ?ERROR("mysql undefined result:~w", [Res]),
    {error, undefined}.

**Comment by vebeter** [comment]
And then ,I tried to just use ?UTF8MB3 , modify mysql_protocol.erl, 
%%
character_set(_ServerVersion) ->
    ?UTF8MB3.

mnesia:insert(#daily_data{id=1,data=[]}).
It seems also  show the warning  about utf8;
Warning 1300: Invalid utf8 character string: '836A'
 in insert into daily_data(`id`,`data`) values (1,'僯');

**Comment by zuiderkwast** [comment]
I tried with `mysql` (not poolboy but it should be the same) this and I got a crash:

```Erlang
1> {ok,Pid} = mysql:start_link(Options).
{ok,<0.86.0>}
2> 8> mysql:query(Pid,                                
2> "CREATE TABLE daily_data ("
2> "id bigint(20) unsigned NOT NULL COMMENT 'Key',"
2> "data blob COMMENT 'Daily_data',"
2> "PRIMARY KEY (id)"
2> ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;"
2> ).
ok
3> Query= " insert into daily_data(id,data) values (1,'僯'); ".
[32,105,110,115,101,114,116,32,105,110,116,111,32,100,97,
 105,108,121,95,100,97,116,97,40,105,100,44,100,97|...]
4> mysql:query(Pid, Query).                                    
=ERROR REPORT==== 7-Jul-2021::10:52:54.504234 ===
** Generic server <0.86.0> terminating 
** Last message in was {query,[32,105,110,115,101,114,116,32,105,110,116,111,
                               32,100,97,105,108,121,95,100,97,116,97,40,105,
                               100,44,100,97,116,97,41,32,118,97,108,117,101,
                               115,32,40,49,44,39,20719,39,41,59,32],
                              no_filtermap_fun,default_timeout}
** When Server state == {state,[5,5,5],
                               37,#Port<0.8>,gen_tcp,[],undefined,"localhost",
                               3306,"otptest","otptest",undefined,[],[],
                               <<"mysql_native_password">>,
                               <<97,45,90,93,70,38,41,59,46,115,122,45,110,98,
                                 35,35,36,44,81,52,0>>,
                               [],true,false,5000,infinity,infinity,60000,0,2,
                               0,0,[],undefined,
                               {dict,0,16,16,8,80,48,
                                     {[],[],[],[],[],[],[],[],[],[],[],[],[],
                                      [],[],[]},
                                     {{[],[],[],[],[],[],[],[],[],[],[],[],[],
                                       [],[],[]}}},
                               empty,false}
** Reason for termination == 
** {badarg,[{erlang,iolist_to_binary,
                    [[32,105,110,115,101,114,116,32,105,110,116,111,32,100,97,
                      105,108,121,95,100,97,116,97,40,105,100,44,100,97,116,
                      97,41,32,118,97,108,117,101,115,32,40,49,44,39,20719,39,
                      41,59,32]],
                    []},
            {mysql_protocol,query,6,
                            [{file,"src/mysql_protocol.erl"},{line,200}]},
            {mysql_conn,query,4,[{file,"src/mysql_conn.erl"},{line,611}]},
            {mysql_conn,handle_call,3,
                        [{file,"src/mysql_conn.erl"},{line,301}]},
            {gen_server,try_handle_call,4,
                        [{file,"gen_server.erl"},{line,661}]},
            {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,690}]},
            {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
** Client <0.83.0> stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,169}]},
    {gen_server,call,3,[{file,"gen_server.erl"},{line,219}]},
    {mysql,query_call,2,[{file,"src/mysql.erl"},{line,835}]},
    {erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,684}]},
    {shell,exprs,7,[{file,"shell.erl"},{line,686}]},
    {shell,eval_exprs,7,[{file,"shell.erl"},{line,642}]},
    {shell,eval_loop,3,[{file,"shell.erl"},{line,627}]}]

=CRASH REPORT==== 7-Jul-2021::10:52:54.519441 ===
...
```

As you can see, the reason for the crash is `iolist_to_binary` called with a list of unicode codepoints (where the Chinese character is 20719) but it needs a list of byte values (0..255). It seems like it is not possible to send the query like this. I this how you sent the query?

When I try a binary UTF-8 encoded query, `Query = <<"insert into daily_data(id,data) values (1,'僯');"/utf8>>.`, it works without warnings.

The UTF-8 encoding for 僯 is three bytes:

```Erlang
5> <<"僯"/utf8>>.
<<229,131,175>>
```

**Comment by vebeter** [comment]
Thanks reply again, 
Yep,when I use , "Query= " insert into daily_data(id,data) values (1,'僯'); ",  "   ,    I will get same errors.
 

But my module is like that:
 Mnesia Use :   mnesia:insert(#daily_data{id=1,data=[]}).
  Params ===>   Id = 5,  Data = term_to_binary([]),
  Table="daily_data",     Vals=[5,<<131,106>>]  .

insert(Table,Vals) ->
  Sql =
        [<<"insert into ">>, Table, <<"(">>, field_join(Fields, false),
            <<") values (">>, val_join(Vals), <<");">>],
  fetch(Query).


fetch(Query) ->
  Pool = 'db_mysql_server_pool',
  TimeOut = 60000,
   mysql_poolboy:query(Pool , Query, TimeOut ).



field_join([], _) ->
    [];
field_join([H | T], true) ->
    [$`, H, $`] ++ [[$,, $`, X, $`] || X <- T];
field_join([H | T], false) ->
    [H] ++ [[$,, X] || X <- T].

val_join([]) ->
    [];
val_join([H | T])->
    [encode(H)] ++ [[$,, encode(X)] || X <- T].

encode(Val) ->
	encode(Val, false).
encode(Val, false) when Val == undefined; Val == null ->
	"null";
encode(Val, true) when Val == undefined; Val == null ->
	<<"null">>;
encode(Val, false) when is_binary(Val) ->
	binary_to_list(quote(Val));
encode(Val, true) when is_binary(Val) ->
	quote(Val);
encode(Val, true) ->
	list_to_binary(encode(Val,false));
encode(Val, false) when is_atom(Val) ->
	quote(atom_to_list(Val));
encode(Val, false) when is_list(Val) ->
	quote(Val);
encode(Val, false) when is_integer(Val) ->
	integer_to_list(Val);
encode(Val, false) when is_float(Val) ->
	[Res] = io_lib:format("~w", [Val]),
	Res;
encode({datetime, Val}, AsBinary) ->
	encode(Val, AsBinary);
encode({{Year, Month, Day}, {Hour, Minute, Second}}, false) ->
	Res = two_digits([Year, Month, Day, Hour, Minute, Second]),
	lists:flatten(Res);
encode({TimeType, Val}, AsBinary)
	when TimeType == 'date';
	TimeType == 'time' ->
	encode(Val, AsBinary);
encode({Time1, Time2, Time3}, false) ->
	Res = two_digits([Time1, Time2, Time3]),
	lists:flatten(Res);
encode(Val, _AsBinary) ->
	{error, {unrecognized_value, Val}}.

two_digits(Nums) when is_list(Nums) ->
	[two_digits(Num) || Num <- Nums];
two_digits(Num) ->
	[Str] = io_lib:format("~b", [Num]),
	case length(Str) of
		1 -> [$0 | Str];
		_ -> Str
	end.

%%  Quote a string or binary value so that it can be included safely in a
%%  MySQL query.
quote(String) when is_list(String) ->
	[39 | lists:reverse([39 | quote(String, [])])];	%% 39 is $'
quote(Bin) when is_binary(Bin) ->
	list_to_binary(quote(binary_to_list(Bin))).

quote([], Acc) ->
	Acc;
quote([0 | Rest], Acc) ->
	quote(Rest, [$0, $\\ | Acc]);
quote([10 | Rest], Acc) ->
	quote(Rest, [$n, $\\ | Acc]);
quote([13 | Rest], Acc) ->
	quote(Rest, [$r, $\\ | Acc]);
quote([$\\ | Rest], Acc) ->
	quote(Rest, [$\\, $\\ | Acc]);
quote([39 | Rest], Acc) ->		%% 39 is $'
	quote(Rest, [39, $\\ | Acc]);	%% 39 is $'
quote([34 | Rest], Acc) ->		%% 34 is $"
	quote(Rest, [34, $\\ | Acc]);	%% 34 is $"
quote([26 | Rest], Acc) ->
	quote(Rest, [$Z, $\\ | Acc]);
quote([C | Rest], Acc) ->
	quote(Rest, [C | Acc]).

**Comment by vebeter** [comment]
And then , the sql wil like  this :
[<<"insert into ">>,"daily_data",<<"(">>, ["`id`",[44,"`data`"]],<<") values (">>, ["522",[44,[39,131,106,39]]],<<");">>].

**Comment by vebeter** [comment]
Hi~ Thanks for help~ It seems I solved the warning.
Template : [<<"insert into ">>,"daily_data",<<"(">>, ["id",[44,"data"]],<<") values (">>, ["522",[44,[39,131,106,39]]],<<");">>].

To add： "_binary "  
SQl: [<<"insert into ">>,"daily_data",<<"(">>, ["id",[44,"data"]],<<") values (">>, ["522",[44, "_binary " ++[39,131,106,39]]],<<");">>].

This is equivalent to :
 insert into daily_data(id,data) values (42, _binary '僯') ;    when I use in mysql command line client.

It will not longer show the warning in BLOB column.

**Comment by vebeter** [comment]
This is equivalent to :
 insert into daily_data(id,data) values (42, _binary '僯') ;    when I use in mysql command line client.

It will not longer show the warning in BLOB column.

**Comment by zuiderkwast** [comment]
Hi!

The bytes `<<131,106>>` is Erlang's `term_to_binary` encoding of an empty list. It's not UTF-8 text.

```Erlang
1> iolist_to_binary([39, 131, 106, 39]) =:= iolist_to_binary(["'",term_to_binary([]),"'"]).
true
```

Instead of your own encode and quote functions, I think you should use a parametrized query and let mysql-otp handle the encoding automatically:

```Erlang
mysql:query(Pid, "insert into daily_data (id, data) values (?, ?)", [5, "僯"]).
```

If you don't want this, then better use `mysql:encode` instead of your own encode. If there is a problem in `mysql:encode` report it to me. :)

**Comment by vebeter** [comment]
Hi~ Thanks reply~
I tried " mysql:query(MysqlConn, "insert into global_daily (id, data) values (?, ?)", [5, " 僯"])." it's fine~.

But  in Erlang ,  I want to use [] ===>  term_to_binary([]) ==> <<131,106>> ,and save  my table at BLOB column in mysql.

And then,  when Erlang VM started , it will  auto-load data to mdb ,ets,  also  match  blob column data , 
so it will binary_to_term( <<131,106>>)  ====> []


I tried mysql_encode:encode(X) to instead of my own encode, It seems get the same warning. I think the problem is should be my function -- val_join(Vals).


Sql is: [<<"insert into ">>,"daily_data",<<"(">>,
                                    ["`id`",[44,"`data`"]],
                                    <<") values (">>,
                                    [<<"425">>,[44,[39,<<131,106>>,39]]],
                                    <<");">>]

Warning 1300: Invalid utf8mb4 character string: '836A'
 in insert into daily_data(`id`,`data`) values (425,'僯');

insert(Table,Vals) ->
 %%Table="daily_data",Vals=[636,<<131,106>>],
Sql =
[<<"insert into ">>, Table, <<"(">>, field_join(Fields, false),
<<") values (">>, val_join(Vals), <<");">>],
	MysqlConn =  poolboy:checkout('db_mysql_server_pool'),
	mysql:query(MysqlConn, Sql).


field_join([], _) ->
[];
field_join([H | T], true) ->
[$, H, $] ++ [[$,, $, X, $] || X <- T];
field_join([H | T], false) ->
[H] ++ [[$,, X] || X <- T].

val_join([]) ->
[];
val_join([H | T])->
[mysql_encode:encode(H)] ++ [[$,, mysql_encode:encode(X)] || X <- T].

**Comment by zuiderkwast** [comment]
With (?, ?) you don't need encode. Do you get a warning for this?:

```Erlang
Binary = term_to_binary([]),
mysql:query(Pid, "insert into daily_data (id, data) values (?, ?);", [Id, Binary]),
```

**Comment by vebeter** [comment]
> With (?, ?) you don't need encode. Do you get a warning for this?:
> 
> ```erlang
> Binary = term_to_binary([]),
> mysql:query(Pid, "insert into daily_data (id, data) values (?, ?);", [Id, Binary]),
> ```

No warning , It's fine. 
I think I will use  mysql:query(Conn, Query, Params)  instead of my own encode sql 

Old (warning):
 Sql = [<<"insert into ">>,"daily_data",<<"(">>,["`id`",[44,"`data`"]],<<") values (">>,["4488",[44,[39,131,106,39]]],<<");">>],
mysql:query(Pid,Sql)  , 


New (no warning)
mysql:query(Pid, "insert into daily_data (id, data) values (?, ?);", [Id, Binary])

**Comment by zuiderkwast** [comment]
OK, good!

I don't think there is a bug here, so I think we can close this. Re-open if you still have some problem.
