### ISSUE TITLE
using otp 24 with inet_backend = socket , [{host, {local, "/tmp/mysql.sock"}},{tcp_options,  [{nodelay,Bool}] Option lead to {error, enotsup} Error

### ISSUE THREAD

**Issue by dogtapdsd** [mysql-otp/mysql-otp#179]
Using unix domain socket '{local, "/tmp/mysql.sock"}' to connect mysql will case this issuse.
the otp gen_tcp document explain this compatibility problem
[https://erlang.org/doc/man/gen_tcp.html](url)

> 
The option nodelay is a TCP specific option that is not compatible with domain = local.
When using inet_backend = socket, trying to create a socket (via listen or connect) with domain = local (for example with option {ifaddr, {local,"/tmp/test"}}) will fail with {error, enotsup}.
This does not actually work for inet_backend = inet either, but in that case the error is simply ignored, which is a bad idea. We have choosen to not ignore this error for inet_backend = socket.

**Comment by zuiderkwast** [comment]
Thanks! A PR is very welcome.

**Comment by dogtapdsd** [comment]
[https://github.com/mysql-otp/mysql-otp/pull/184](url)
a PR was impoved and merge into the base branch

**Comment by zuiderkwast** [comment]
#184 replaces #181, but it has not been merged yet. When #184 is merged, this issue will be closed automatically.
