### ISSUE TITLE
Cannot connect to mysql 5.1.73

### ISSUE THREAD

**Issue by walrusVision** [mysql-otp/mysql-otp#18]
I get this error when trying to connect to a database running mysql 5.1.73. The same works fine on 5.5.42 and 5.6.23.

2> mysql:start_link([{user, "otptest"}, {password, "otptest"}]). 
** exception exit: badarg
     in function  binary:last/1
        called as binary:last(<<>>)
     in call from mysql_protocol:parse_handshake/1 (src/mysql_protocol.erl, line 241)
     in call from mysql_protocol:handshake/5 (src/mysql_protocol.erl, line 52)
     in call from mysql:init/1 (src/mysql.erl, line 476)
     in call from gen_server:init_it/6 (gen_server.erl, line 306)
     in call from proc_lib:init_p_do_apply/3 (proc_lib.erl, line 237)

**Comment by zuiderkwast** [comment]
Thanks for the report! I don't have the version to reproduce this, but I assume this fix will solve it. Please test and re-open the issue if the problem persists. I'd appreciate a comment also if it solved your problem. :-)
