### ISSUE TITLE
CI: Switch to GitHub Actions (or something else)

### ISSUE THREAD

**Issue by zuiderkwast** [mysql-otp/mysql-otp#180]
travic-ci.org has stopped working. We need to switch to travis-ci.com, or perhaps to GitHub Actions or something else.

**Comment by zuiderkwast** [comment]
This is kind of urgent. I don't want to merge new stuff without a working CI.

I've tried moving the jobs from travis-ci.org to travis-ci.com, which seems easy for personal repos but not organisations. @juhlig?

**Comment by zuiderkwast** [comment]
This one looks promising: https://github.com/marketplace/actions/actions-setup-mysql

> Available Versions are:
>
> * MySQL
>     *   8.0
>     *   5.7
>     *   5.6
> *   MariaDB
>     *   10.6
>     *   10.5
>     *   10.4
>     *   10.3

**Comment by juhlig** [comment]
> This one looks promising: https://github.com/marketplace/actions/actions-setup-mysql

Yes :) If we can't get it working, we could also ask the maintainer for help I guess.

**Comment by zuiderkwast** [comment]
@Gemrav that's great! After two years, there are probably more and easier ways to install different versions of these databases in github actions.

**Comment by juhlig** [comment]
Fixed by #207.
