### ISSUE TITLE
{{badmatch,{error,econnrefused}}

### ISSUE THREAD

**Issue by 221V** [mysql-otp/mysql-otp#189]
hello!
```
(myapp@127.0.0.1)1> mysql:start_link([{host, "localhost"},{user, "myuser"},{password, "mypass"},{database, "mydb"}]).
Error in process <0.210.0> on node 'myapp@127.0.0.1' with exit value:
{{badmatch,{error,econnrefused}},
 [{mysql_conn,connect_socket,1,
              [{file,"deps/mysql-otp/src/mysql_conn.erl"},{line,160}]},
  {mysql_conn,'-connect/1-fun-0-',2,
              [{file,"deps/mysql-otp/src/mysql_conn.erl"},{line,136}]}]}

** exception exit: {badmatch,{error,econnrefused}}
     in function  mysql_conn:connect_socket/1 (deps/mysql-otp/src/mysql_conn.erl, line 160)
     in call from mysql_conn:'-connect/1-fun-0-'/2 (deps/mysql-otp/src/mysql_conn.erl, line 136)
```
i got this with mysql-otp v1.7.0 and mariaDB 10.1.41, erl 23.3 on Debian 9.3
user + pass + database data are ok, what i can to do with this?

thanks

**Comment by 221V** [comment]
the same with https://github.com/mysql-otp/mysql-otp/tree/00bef88fe05504b32b6de878ea172b833550ce21
;-(

**Comment by 221V** [comment]
upd mariaDB to 10.1.48 -- the same...
upd mariaDB to 10.6.5 -- now works!
thanks! :)

**Comment by zuiderkwast** [comment]
I don't know why you had connection problems. It's good that you solved it.

The `badmatch` error is probably still a bug then.

**Comment by Maria-12648430** [comment]
> The `badmatch` error is probably still a bug then.

https://github.com/mysql-otp/mysql-otp/blob/00bef88fe05504b32b6de878ea172b833550ce21/src/mysql_conn.erl#L163
Yes 😅

**Comment by zuiderkwast** [comment]
I guess we get a better error if we do sth like...

```Erlang
{ok, Socket} = case gen_tcp:connect(Host, Port, SockOpts) of
                   {error, Error} -> exit(Error);
                   Res -> Res
               end,

... since we still need to exit the process. Maria WDYT?

**Comment by Maria-12648430** [comment]
Neat :)
