### ISSUE TITLE
Application name conflict

### ISSUE THREAD

**Issue by essen** [mysql-otp/mysql-otp#19]
Hi, I am currently testing that everything compiles, in the process adding them all to the package index, and would like to add your application as well, however I am running into a problem. Your application's name is the same as the much older https://github.com/dizzyd/erlang-mysql-driver

... and that's all I got, really.

I don't know if they are API and feature compatible (in which case maybe better to switch to this one), and if they're not, then I don't really know how to handle that kind of case.

Thoughts?

**Comment by zuiderkwast** [comment]
They are not API compatible in any way. The name conflict was accepted with the reasoning that nobody would want to use both in the same project.

The old one is probably still in use (in old projects) and listed by Oracle as "the" Erlang driver, though another fork at source forge if i remember correctly. There are many forks of the old one, all with the same name. The original is the one from YXA (2002?) with code that can be found here: https://github.com/fredrikt/yxa/tree/master/src/mysql .

I have made a small overview here: https://github.com/mysql-otp/mysql-otp/wiki/Comparison-of-MySQL-clients

My personal opinion is that this one is the best and the old ones are obsolete.

**Comment by essen** [comment]
Since sending this ticket I found other conflicting application names: uuid, sqerl (of all things!) and syslog. I think I need to devise a solution that allows me to handle conflicts like this.

On the other hand I think you make a good point, this project should be the default 'mysql' project.

Thanks for the info.
