### ISSUE TITLE
compile failed on OTP 25.0-rc1

### ISSUE THREAD

**Issue by bighunter513** [mysql-otp/mysql-otp#193]
when I upgrade to OTP 25.0-rc1, 
# make 
ERLC   mysql.erl mysql_cache.erl mysql_conn.erl mysql_encode.erl mysql_protocol.erl
mysql:1: function transaction/4+27:
  Internal consistency check failed - please report this bug.
  Instruction: {call_last,4,{f,164},4}
  Error:       {bad_arg_type,{x,1},any,{t_fun,any,any,any}}:

make[1]: *** [erlang.mk:500: ebin/mysql.app] Error 1
make: *** [erlang.mk:290: app] Error 2

**Comment by zuiderkwast** [comment]
Thanks. There is no line number within the Erlang code. I don't understand what's wrong. Do you?

**Comment by juhlig** [comment]
See here: https://erlangforums.com/t/otp-25-0-rc1-release-candidate-1-is-released/1084/8

**Comment by juhlig** [comment]
👍
