### ISSUE TITLE
Multiple Statements fails

### ISSUE THREAD

**Issue by posilva** [mysql-otp/mysql-otp#20]
Hi,

first of all thank you for your very nice work with this driver. 

I am trying to run your example of multiple statement and it fails with: 

```erlang
19> mysql:query(PID, "SELECT 42 AS foo; SELECT 'baz' AS bar;").
{error,{1064,<<"42000">>,
        <<"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server ver"...>>}}
```
I am running against a RDS MySQL instance

Best

Pedro

**Comment by zuiderkwast** [comment]
Hi! There is a test for this and the test passes. https://github.com/mysql-otp/mysql-otp/blob/1.0.0/test/mysql_tests.erl#L207

Which version are you using? Multi statements were added fairly recently. Also do you know which version of MySQL is used on RDS? Normally the handshake should fail if the server doesn't support the features required by the driver, but I have no time to look into this at the moment.

**Comment by zuiderkwast** [comment]
Can not reproduce. Open again if this is still a problem.
