### ISSUE TITLE
nulterm_str vs get_null_terminated_binary

### ISSUE THREAD

**Issue by silviucpp** [mysql-otp/mysql-otp#205]
Hello,

This is not an issue with the library. It's just a curiosity. 

Looking to the code get_null_terminated_binary and nulterm_str are doing the same thing, only difference I notice is that in case
of nulterm_str if null is not present will crash. 

Do I miss something ?
Silviu

**Comment by zuiderkwast** [comment]
Hi!

I don't remember. :)

**Comment by silviucpp** [comment]
Ohh ok !
