### ISSUE TITLE
Replace character "?"

### ISSUE THREAD

**Issue by BessNebel** [mysql-otp/mysql-otp#24]
Hi! I got strange behavior, when i try execute 
`mysql:query(Pid, "UPDATE table SET ?=1 WHERE id=1", [<<"column">>])`
 i got error `"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?=1' at line 1"`. Seems like driver do not replace "?" to "column". I am using 10.0.19-MariaDB.

**Comment by zuiderkwast** [comment]
The ? character is not a general purpose search and replace. It is a placeholder for a value. Please look at the MySQL manual to learn how to use prepared statements.

**Comment by zuiderkwast** [comment]
Btw, the driver does not substitute `?`. It is done by the mysql server.
