### ISSUE TITLE
decode_binary(#col{type = ?TYPE_FLOAT}, ...) fails when the input value is 0.0

### ISSUE THREAD

**Issue by ionuthristodorescu** [mysql-otp/mysql-otp#27]
decode_binary(#col{type = ?TYPE_FLOAT},
              <<Value:32/float-little, Rest/binary>>) ->
    ...
    Factor = math:pow(10, floor(6 - math:log10(abs(Value)))),

When Value is 0.0, log10() is badarith'ing. 0.0 is obviously a valid value.

**Comment by zuiderkwast** [comment]
Good catch. The solution would be a separate function clause for the 0.0 float. Don't forget to add a testcase.

**Comment by ionuthristodorescu** [comment]
The fix is simple indeed, but how do I run the tests ? I get the error below when I do make eunit :

 APP    mysql.app.src
 GEN    test-dir
 GEN    eunit
mysql_tests: query_test_ (Basic queries)...*failed*
in function mysql_tests:'-basic_queries/1-fun-1-'/2 (test/mysql_tests.erl, line 184)
in call from mysql_tests:basic_queries/1 (test/mysql_tests.erl, line 184)
**error:{assertEqual_failed,[{module,mysql_tests},
                     {line,184},
                     {expression,"mysql : warning_count ( Pid )"},
                     {expected,1},
                     {value,2}]}


mysql_tests: query_test_ (Multi statements)...*failed*
in function mysql_tests:multi_statements/1 (test/mysql_tests.erl, line 222)
**error:{badmatch,{error,{1728,<<"HY000">>,
                  <<"Cannot load from mysql.proc. The table is probab"...>>}}}

Please advice.

**Comment by zuiderkwast** [comment]
"Cannot load from mysql.proc. The table is probably corrupted". Try google that. It seems you should run a command to repair mysql data files.
