### ISSUE TITLE
param undefined exception

### ISSUE THREAD

**Issue by aposto** [mysql-otp/mysql-otp#30]
````erlang
no function clause matching mysql_protocol:encode_param(undefined) line 737
````

I think **undefined** should handle the **null**.

**Comment by zuiderkwast** [comment]
I understand it might be handy but I think we should not accept `undefined`. I prefer a single representation of the SQL NULL and I chose the atom `null` for this. It is always returned as `null` from the server.

There is nothing special with the `undefined` atom. It just happens to be a default value returned by some OTP functions for dicts and proplists (note: not for `maps:get/2`). If you send `undefined` to the database, this may indicate that you have a bug in your program. Crashing is the way to detect the bug early. That is my argument for not accepting undefined.

In general I would say that synonyms (or implicit conversions) like this is not the Erlang way. For comparison, in Erlang the boolean operators `and` and `or` only accepts `true` and `false` as operands and crashes on any other values such as `0`, `1` or `undefined`. Some other languages such as JavaScript would try to guess what you mean and converts 0, null and undefined to false, etc.

**Comment by ddosia** [comment]
I found path of some json libraries follows quite frustrating, they use `null` and `undefined` as synonyms, whereas semantically `null` it is explicit value and `undefined` is *absence* of value.
When you construct sql statement, say, "SET id = NULL", is not the same as just omit this at all (db may put different default value instead).

**Comment by zuiderkwast** [comment]
I see. So @ddosia you think we should accept undefined as a synonym? We can do it if that's what people want.

**Comment by ddosia** [comment]
No, I strongly against this synonym. Imo, these two atoms have different meaning.

**Comment by zuiderkwast** [comment]
Ok, so the two of us agree on not adding the synonym. If the discussion comes up again, feel free to re-open this issue.
