### ISSUE TITLE
replace error(old_server_version)

### ISSUE THREAD

**Issue by ingwinlu** [mysql-otp/mysql-otp#31]
so I recently had the pleasure to deploy to an older mysql version(5.1) and encountered the old_server_version error.

It would be much nicer to try and continue if possible and just not offer some of the features that are tested during the handshake (I only needed 1 simple query to get some data).

If that is not reasonable, it would at least be good to know which versions of popular sql servers are supported and what features are missing for mysql-otp to work in the error output.

**Comment by zuiderkwast** [comment]
5.1 really should work. If it doesn't this is definitely a bug. Any version from 4.1 and up should work.

**Comment by ingwinlu** [comment]
since I wasn't the one deploying and only got the error log in a mail I can't really provide more input.
The person responsible said that they had `Server version: 5.1.56 MySQL Community Server (GPL) by Remi` installed (on centos 7).

Maybe it was one of the other requirements that lead to the error (i.e. no multi statements)? Which would reinforce my need to error out with the exact reason instead of just `old_server_version`.

**Comment by zuiderkwast** [comment]
Right, it's the MULTI_* capability flags that caused the bug. It is actually caused by this bug in the server: http://bugs.mysql.com/bug.php?id=42268 . There is a workaround as you can read in the comments. I'm on it now.

**Comment by zuiderkwast** [comment]
Too bad Travis can't run tests on multiple MySQL server versions. That would have been really useful.

Thanks for the report!

**Comment by ingwinlu** [comment]
cheers, I will try and ask my client to deploy an updated version to see if that fixed it. They found a newer mysql version on another machine somewhere and moved the db there so I am not sure if they are still interested though.

**Comment by ingwinlu** [comment]
Just got confirmation that the fix indeed resolved the issue we had in deployment. Thanks!
