### ISSUE TITLE
bulk insert

### ISSUE THREAD

**Issue by vde-edv** [mysql-otp/mysql-otp#32]
Is there a way to pass multiple records in a single INSERT query?

    6> mysql:query( C, "INSERT INTO mytable (id, bar) VALUES (?, ?)", [33, 33]).
    ok
    7> mysql:query( C, "INSERT INTO mytable (id, bar) VALUES (?, ?)", [[33, 33], [44,44]]). 
    ok
    8> 
    =WARNING REPORT==== 13-Sep-2015::23:47:22 ===
    Warning 1366: Incorrect integer value: '!!' for column 'id' at row 1
    Warning 1366: Incorrect integer value: ',,' for column 'bar' at row 1
     in INSERT INTO mytable (id, bar) VALUES (?, ?)

Command 7 just inserts (0,0 )-: 

I am asking because in another project (java) I observed that a few bulk inserts caused less CPU load  time than many single INSERTs.

**Comment by zuiderkwast** [comment]
I like the idea.

Obviously it could be implemented using a prepared statement that is executed once for each value row. I'm not sure it would be more CPU efficient but it could be useful anyway.

**Comment by zuiderkwast** [comment]
How do we know if it's a bulk insert or a single row?

Your example is very good in demonstrating the problem. You are inserting two strings: `"!!"` and `",,"`. There is no way to know that you want to insert two rows of integers instead of one row of two strings.

**Comment by vde-edv** [comment]
I suppose we need a list of fields before VALUES to decide. Or (easier) add a new convention : to pass multiple records, pass a tuple of lists, each list representing a single record.

**Comment by zuiderkwast** [comment]
So, if I get you right, you suggest using a tuple as a list of rows, like this: `mysql:query(C, "INSERT INTO mytable (id, bar) VALUES (?, ?)", {[33, 33], [44,44]}).`? I don't like that. That's not what tuples are for.

Another idea would be to add a new function name for this, e.g. `mysql:multi_query(C, "INSERT INTO mytable (id, bar) VALUES (?, ?)", [[33, 33], [44,44]])` where the parameter list is always a list of lists. In this way, it is more explicit and distinct from the simple case.

But to be honest, I don't think bulk insert is very useful, at least not for performance. When you execute a parametrized query, the mysql gen_server is creating a prepared statement which is cached and the next time you do the same query, the same prepared statement already exists and it will be re-used. So executing the query multiple times using `lists:foreach/2` is explicit, yet efficient.

If the MySQL protocol would have special support for bulk queries, the situation would be different, but it hasn't. The prepared statement must be executed on the server once for each row. Having a special syntax for bulk queries would hint to the user that it is more efficient than doing separate calls, which it isn't.

The only way to actually insert multiple rows with a single round-drip to the server is to do them in a single query: `mysql:query(C, "INSERT INTO mytable (id, bar) VALUES (33, 33), (44, 44)")`.

So, after thinking about this for a while, I think this should not be implemented. I'm closing the issue but feel free to continue the discussion.

**Comment by zuiderkwast** [comment]
Just one thing on this topic: Multiple inserts are faster inside a transaction.
