### ISSUE TITLE
Detect server shutdown

### ISSUE THREAD

**Issue by zuiderkwast** [mysql-otp/mysql-otp#33]
When the server shuts down cleanly it sends a TCP message to notify us that it is closing the connection. We do not detect this because our gen_tcp connection is in passive mode.

Solution: Set the connectionn to `{active, once}` and listen for info message `{tcp_closed, _Socket}`. Stop the gen_server when this happens (so that some supervisor or pool can start a new connection). Before any communication with the server (such as when we send a query) we should set the connection back to passive mode, do the communication and afterwards set it back to active once.

Note that we cannot detect a network split or a server crash. In this case there is no TCP message that tells us that the connection is gone.

Related issues: #22, #25 and https://github.com/mysql-otp/mysql-otp-poolboy/issues/14

**Comment by sngyai** [comment]
Has it been solved?

**Comment by zuiderkwast** [comment]
No. How important is this to you? A pull request is welcome. I would bump the version to 2.0.0 when this feature is solved.

**Comment by newsdy** [comment]
Has it been solved? I have the same problem

**Comment by alexshavelev** [comment]
think i will do it in 1-2 days

**Comment by alexshavelev** [comment]
#39 hope it will help

**Comment by zuiderkwast** [comment]
Closed by PR #41 (which was greatly inspired by #39). Thanks @johlo and @alexshavelev!

**Comment by zuiderkwast** [comment]
I wrote earlier that I would bump the version to 2.0.0 when this feature is solved, but since this feature is not breaking any backwards compatibility, there is no reason to bump the major version. I have bumped the minor version to 1.2.0.
