### ISSUE TITLE
Support connection with no password

### ISSUE THREAD

**Issue by povloid** [mysql-otp/mysql-otp#36]
Hi!!
is it possible, can you realize support for connection with no password?
like in mysql, it work in this example:

`mysql -u root -h host database`

but not work in your driver

`{ok, Pid} = mysql:start_link([{host, "host"}, {user, "root"},{database, "database"},{password, []}]). `
or
`{ok, Pid} = mysql:start_link([{host, "host"}, {user, "root"},{database, "database"}}]). `

it's not work

**Comment by wk8** [comment]
Should be fixed by https://github.com/mysql-otp/mysql-otp/pull/37
