### ISSUE TITLE
Support LOAD DATA LOCAL INFILE

### ISSUE THREAD

**Issue by redink** [mysql-otp/mysql-otp#38]
Hello,
First, thanks for this repo, I replace mysql driver via `mysql-otp`. But, I found this driver can not support `LOAD DATA LOCAL INFILE`, just like:

```
LOAD DATA LOCAL INFILE '/path/myfile' INTO TABLE table_name;
```

is it possible, can you realize support for `LOAD DATA LOCAL INFILE`?

Thanks again.

**Comment by zuiderkwast** [comment]
It would be a nice feature. I don't have time to implement it myself at the moment but feel free to implement it and submit a pull request.
