### ISSUE TITLE
How to install it with mysql database?

### ISSUE THREAD

**Issue by kenpeter** [mysql-otp/mysql-otp#40]
Hi,

I git clone the project, then run make. How do I install it with mysql database? Currently, I am running Ubuntu 16.04.

**Comment by zuiderkwast** [comment]
This is a client driver for connecting to a mysql server. If you don't have a mysql server, you need to install one. On Debian, you can do `apt-get install mysql-server`. On Ubuntu I don't know but I guess it is the same as on Debian.
