### ISSUE TITLE
Does not support JSON type field

### ISSUE THREAD

**Issue by mango009** [mysql-otp/mysql-otp#46]
MySQL 5.7.8 forward supports JSON type fields. But mysql-otp does not seem to support it. I got error message such as the following when retrieving a record having JSON field:

** Reason for termination == 
** {function_clause,[{mysql_protocol,decode_text,
                                     [{col,<<"blob">>,245,63,4294967295,0,144},
                                      <<"[\"javascript\", \"es2015\", \"json\"]">>],
                                     [{file,"src/mysql_protocol.erl"},
                                      {line,454}]},
                     {mysql_protocol,decode_text_row_acc,3,
                                     [{file,"src/mysql_protocol.erl"},
                                      {line,446}]},
                     {mysql_protocol,'-parse_resultset/3-lc$^0/1-0-',3,
                                     [{file,"src/mysql_protocol.erl"},
                                      {line,359}]},
                     {mysql_protocol,parse_resultset,3,
                                     [{file,"src/mysql_protocol.erl"},
                                      {line,359}]},
                     {mysql_protocol,fetch_response,5,
                                     [{file,"src/mysql_protocol.erl"},
                                      {line,323}]},

**Comment by johlo** [comment]
I've opened a PR for this, cc @zuiderkwast

**Comment by zuiderkwast** [comment]
Solved in PR #47.
