### ISSUE TITLE
License inconsistency

### ISSUE THREAD

**Issue by johlo** [mysql-otp/mysql-otp#50]
The README says LGPL is used, but GPL is shown in the github "status bar" (or whatever it is). You need to update the project settings in github to make it LGPL?

**Comment by zuiderkwast** [comment]
LGPL is GPL with an exeption. It is recommended by FSF to put them in COPYING and COPYING.LESSER, respectively. In the github "status bar" it says GPL but when you click it, COPYING.LESSER will be displayed, i.e. the LGPL text. I don't know what Github is doing but I think we are doing it in the right way in the repo. I don't think there is a license setting for the repo. It probably just scans the repo for license files.

Do you think there anything we could do? Any suggestions?

**Comment by johlo** [comment]
You are right, I can't find any info on how to change this. 
Github's confusion might come from the presence of both COPYING and COPYING.LESSER, if they scan the repo it might find COPYING (GPL) first and use that one, but I don't know if they re-scan the repos periodically.

Now I'm getting curious about how it works, will try removing COPYING in my fork to see if github updates itself :)

**Comment by johlo** [comment]
Ok, so I played around with this a bit and found out how to make GH update the license tag to LGPL.

Simply delete the COPYING.LESSER file (and push) and then re-add it (and push), that's it. Worked for me on a fork (I've removed the fork now).
It looks like it has to be done directly on the `master` branch, so I don't think I can open a PR for this. @zuiderkwast needs to do it.

**Comment by zuiderkwast** [comment]
Finally, I did as you said. :-) Thanks for the solution! (I force-pushed so it is not visible in the commit history.)

**Comment by johlo** [comment]
Nice! 👍
