### ISSUE TITLE
Problems with decimal columns

### ISSUE THREAD

**Issue by silviucpp** [mysql-otp/mysql-otp#52]
Hello,

I have the following test schema:

``` sql
CREATE TABLE `test_decimals` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `balance` decimal(13,4) NOT NULL DEFAULT '0.0000',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8;

INSERT INTO test_decimals(id, balance) VALUES(1, 5000);
```

And the following code snippet:

``` erlang
-module(test_decimal).

-export([start/0, exec/1]).

start() ->
    {ok, Pid} = mysql:start_link([
        {host, "127.0.0.1"},
        {port, 3306},
        {user, "root"},
        {password, "root"},
        {database, "test_db"},
        {keep_alive, 300000},
        {queries, [<<"set names 'utf8';">>]},
        {prepare, [{debit_account, <<"UPDATE test_decimals SET balance = balance - ? WHERE id = ?">>}]}
    ]),

    Pid.

exec(Pid)->
    mysql:execute(Pid, debit_account, [10.2, 1]).
```

If you run `Pid = test_decimal:start().` to create a connection and then run several times `test_decimal:exec(Pid).` you will notice from time to time the following warning:

``` erlang
[warning] Note 1265: Data truncated for column 'balance' at row 1
 in UPDATE test_decimals SET balance = balance - ? WHERE id = ?
```

I tested the same query with `mysql workbench`, `emysql` client, and also the mysql console and I cannot see this warning.

I'm sure is related on how floats are encoded in `mysql-otp` in prepared statements. 

Any Idea how I can get rid of this problem ?

Silviu

**Comment by zuiderkwast** [comment]
Thank you for the report! The data is sent in a different way for prepared statements (binary protocol) compared to plain queries (text protocol). Emysql is using only the text protocol.

In the text protocol, the number is basically represented as the string "10.2". In the binary protocol, the float value is sent as a double encoded as 64 bit little endian in mysql_protocol (https://github.com/mysql-otp/mysql-otp/blob/master/src/mysql_protocol.erl#L778).

```Erlang
encode_param(Value) when is_float(Value) ->
    {<<?TYPE_DOUBLE, 0>>, <<Value:64/float-little>>};
```

Decimals are exact while floats are .... well ,floats (e.g. 10.2 is not exact when represented as a float) so using a float in Erlang is may not be the perfect solution if you want to keep the precition of the DECIMAL column. Have you tried sending it as a string or binary, i.e. `<<"10.2">>`?

**Comment by silviucpp** [comment]
Hello, 

I tried sending as <<"10.2">> and it;s the same. also sending as string with all clients gives the same warning. 

Silviu

**Comment by silviucpp** [comment]
Hello Viktor,

Do you have any idea about how can this problem be solved ?

Silviu

**Comment by zuiderkwast** [comment]
No... I know that emysql doesn't show warnings. Maybe there are warnings there too but you don't see them. Could that be?

Do you get warnings if you do the query without prepared statements?

**Comment by silviucpp** [comment]
I don't think there are warnings there because of the textual protocol. I tested with Mysql Workbench and there I can see the warnings in case of I use 10.2 as string. But when using as numeric there is no error. 
I tested something like:

PREPARE stmt1 FROM 'UPDATE test_decimals SET balance = balance - ? WHERE id = ?';
 
SET @balance= 10.2;
SET @id=1;
EXECUTE stmt1 USING @balance, @id;

Silviu

**Comment by silviucpp** [comment]
Hello I found a way to encode floats from erlang properly to work with mysql columns like float and decimal without any warnings.

    encode_param(Value0) when is_float(Value0) ->
        Value = float_to_binary(Value0),
        EncLength = lenenc_int_encode(byte_size(Value)),
        {<<?TYPE_DECIMAL, 0>>, <<EncLength/binary, Value/binary>>};

I tested with both and seems fine. and I didn't saw any warning.

What do you think ?

Kind regards,
Silviu

**Comment by zuiderkwast** [comment]
That looks good to me! As long as it works with both new and old MySQL such as 4.1.

**Comment by silviucpp** [comment]
Hello,

Do you have any way to test the oldest mysql server you want to support ? I tested only 5.6 and 5.7 and seems working fine both.

Silviu

**Comment by zuiderkwast** [comment]
Two years ago I had a way to run 4.1 (using MacPorts on my old mac) but maybe it's not so easy to get MySQL 4.1 anymore. Anyway, TYPE_DECIMAL has value 0 so I assume it has been there in old versions too.

Another question: In which Erlang/OTP version was `float_to_binary/0` added? I believe it is not that old, maybe 17.0? Currently this driver supports R16B (if i'm not mistaken). Anyway, that should be covered by Travis CI so feel free to make a PR.

**Comment by silviucpp** [comment]
Hello,

Seems like: float_to_binary(10.2) for example is represented as a string like:

<<"1.01999999999999992895e+01">> which is not ok. 

I propose to use:

float_to_binary(10.2, [{decimals, 8}, compact]).

which represent it as :

<<"10.2">>

Do you have any preference on the decimals number ? anyway because of the compact option all 0's will be trimmed 

Silviu

**Comment by zuiderkwast** [comment]
Truncating the fractions will lose precision in other cases. I don't like this idea anymore. :-/

The problem with floats is that the float 10.2 is not equal to the real number 10.2. Already in Erlang 10.2 is represented as a 64-bit float so converting it to text will not solve anything other than possibly hiding the warnings from MySQL. But losing precision is worse IMO. Currently the float is sent to MySQL the way it is represented in memory in Erlang.

A way to send the exact number 10.2 from Erlang to MySQL is by representing it as a string or binary in Erlang and convert it on the MySQL side, e.g. like this

```Erlang
mysql:query(Pid,
            "UPDATE tab SET value = CAST(? AS DECIMAL(11, 8)) WHERE id = ?",
            [<<"10.2">>, 42]).
```

**Comment by silviucpp** [comment]
Hi,

Sounds fair and I understand your concern. Even if I doubt anyone that needs more than 14 decimals precision and will work with floats.

On my side I already have a lot of decimal columns and I know that I never need more than 4 decimals so I'll use a fork with the above fix which should cover me without having lot of regressions

Siviu

**Comment by zuiderkwast** [comment]
Hi @silviucpp! I'm reopening this after many years because I see that you're still using a fork to be able to do what you want. That means that you (and maybe others too) have some use case that mysql-otp can't solve, which is unfortunate.

I was thinking we can add one or both of this way to send floats:

1. add some kind of configuration for sending floats as decimals with a configurable number of digits
2. add a special way to send decimals such as `{decimal, <<"10.2">>}` or `{decimal, 10.2}` where the number is "rounded" using `io_lib:format("~w", [10.2])` which is not exactly the same as `binary_to_float/1` but there's still some kind of rounding.

I still think rounding floats for FLOAT and DOUBLE columns is wrong though, for a few reasons:

* When the SQL type DOUBLE is used, it's exactly same representation as in the Erlang value, so it's desirable to have an exact copy without precision loss in both directions.
* The text protocol and the binary protocol should give the result. The stored value should not depending on which protocol is used.
* Changing the default behaviour would not be backwards compatible.

What do you think?

**Comment by silviucpp** [comment]
hdello @zuiderkwast I like the idea to  add some kind of configuration for sending floats as decimals with a configurable number of digits.

Related to:

**The text protocol and the binary protocol should give the result. The stored value should not depending on which protocol is used.**

This is false anyway with the current version of mysql-otp. The drivers using textual protocols encode the 10.2 as <<"10.2">> while the binary one as 1.01999999999999992895e+01 ..

Personally all the time when working with floats I have the precision set for the entire app. so having a setting in mysql-otp will be great !

Silviu

**Comment by zuiderkwast** [comment]
>> The stored value should not depending on which protocol is used.
> 
> This is false anyway with the current version of mysql-otp. The drivers using textual protocols encode the 10.2 as <<"10.2">> while the binary one as 1.01999999999999992895e+01 ..

Well, as floats, these two actually represent exactly the same value:

```Erlang
1> 1.01999999999999992895e+01 =:= 10.2.
true
```

... so in Erlang or any other language where floats are used, they are the same, but of course, as DECIMALs, they are different.

> I propose to use:
>
> `float_to_binary(10.2, [{decimals, 8}, compact]).`

We can use `io_lib:format("~w", [10.2])` instead of `float_to_binary(10.2)`. Then we don't need to decide on a fixed number of decimals.

I want to add a possibility to send values as `{decimal, 10.2}` which sends them encoded as TYPE_DECIMAL.

I can also add an option `{float_as_decimal, boolean() | non_neg_integer()}` where if you set a number, `float_to_binary(10.2, [{decimals, N}, compact])` is used and otherwise `io_lib:format` is used. Sounds good?

**Comment by silviucpp** [comment]
Sounds good !

Silviu
