### ISSUE TITLE
Mysql command timeout is really short, should be longer

### ISSUE THREAD

**Issue by RaoH** [mysql-otp/mysql-otp#53]
`?cmd_timeout` (https://github.com/mysql-otp/mysql-otp/blob/master/src/mysql.erl#L48) is set to 3 seconds. It seems a bit short when looking at other clients that has 30 seconds. 

Example clients: https://dev.mysql.com/doc/connector-net/en/connector-net-programming-mysqlcommand.html defaults to 30 seconds, but is configurable.

We discovered the issue when issuing a large commit and the database had big load.

So should we only bump the timeout to 30 seconds?
Or should it be configurable.

**Comment by zuiderkwast** [comment]
It is used in `commit` and that takes time? OK, change it then. But note that gen_server:call has a default timeout of i think 5 seconds.

I used this macro for calls that *shouldn't* take time. For other things that could be slow (such as query) the user can specify a timeout in the call. Maybe we can add another macro, say ?commit_timeout, just for commit (and maybe also rollback if that is slow too?) and still have the short timeout for other commands that are never slow (e.g. ping and other stuff).

For the `gen_server:call(Conn, commit)`, put a timeout that is ?commit_timeout plus 1 second or something like that. I.e. `gen_server:call(Conn, commit, ?commit_timeout + 1000)`..

Makes sense?
