### ISSUE TITLE
Applications in mysql.app.src file

### ISSUE THREAD

**Issue by Pouriya-Jahanbakhsh** [mysql-otp/mysql-otp#57]
Why `mysql` has not any application like `kernel` or `stdlib` in its `.app.src` file ?
Empty applications list mades a problem for me, [The problem](https://github.com/erlware/relx/issues/566)

**Comment by slezakattack** [comment]
Because this is a library, not an application. You'll notice that this doesn't follow the normal OTP application convention (app behavior or application supervisor), therefore the application value is an empty array as there is nothing to start. Hope this helps.
