### ISSUE TITLE
Optionally replace Erlang error_logger with custom logger

### ISSUE THREAD

**Issue by slezakattack** [mysql-otp/mysql-otp#60]
When logging warnings, the library uses Erlang's error_logger which is known to have scalability issues. A lot of Erlang applications tend to use other logging solutions such as lager. Would like to know if it would be acceptable to add a feature where a user of this library can override the logging function through a config? Perhaps leave the default as error_logger if not specified?

I can work/implement this feature but thought it would be good to bring it up in case there are opinions on this.

**Comment by slezakattack** [comment]
#62

**Comment by zuiderkwast** [comment]
See the discussion on #62.

`Error_logger` is the standard OTP interface to logging, thus we will keep that as it is for now. It is possible to disable the default logging and plug in other logging (e.g. Lager) to the default error_logger. Examples/howtos on this are welcome.
