### ISSUE TITLE
Rows affected vs Rows matched in update

### ISSUE THREAD

**Issue by adrianboston** [mysql-otp/mysql-otp#63]
I see the rows affected function; is it possible to add a "rows_matched" function so its feasible to distinguish between a query not found and a query found but an update not changed. Currently one must do two ops.

Here is the response inside mysql shell.
Query OK, 0 rows affected (0.00 sec)
Rows matched: 1  Changed: 0  Warnings: 0

**Comment by silviucpp** [comment]
Check {found_rows, boolean()} setting.

Silviu

**Comment by adrianboston** [comment]
This doesn't appear to be working when used with its comrade poolboy. Although mysql-otp-poolboy is pulling from mysql-otp. Any particular version this feature came in on. And can it be used per query versus on a 'global' level.

**Comment by silviucpp** [comment]
Hello the setting is per-connection not per query. I'm not familiar with mysql-poolboy. I have created another pool based on mysql-otp https://github.com/silviucpp/mysql_pool 

If in your pool setting s you put:
```erlang
{mysql_pool, [
        {pools, [
            {pool_one, [
                {size, 10},
                {connection_options, [
                    {host, "localhost"},
                    {user, "root"},
                    {password, "root"},
                    {database, "db_name"},
                    {found_rows, true}
                ]}
            ]}
        ]}
    ]}
```

and do :

```erlang
{ok, FoundRows} = mysql_pool:execute(pool_one, update_account_stm_id, [UsrId], affected_rows).
```
Basically my pool offers a version of the `execute` where you can specify to return number of affected rows or last insert id. You can check the documentation for more details.

I'm not sure what exactly is not working for you

**Comment by zuiderkwast** [comment]
Solved? I'm closing this. Feel free to re-open if this is still an issue.
