### ISSUE TITLE
Is there a way to get back the results of a query as a map?

### ISSUE THREAD

**Issue by fabianTMC** [mysql-otp/mysql-otp#64]

**Comment by johnzeng** [comment]
I don't know, I write one for it...

```
```

**Comment by snailman** [comment]
another way:

%%
%% @doc package row data as a map
as_maps(undefined, undefined) ->
    [];
as_maps(Fields, undefined)
    when is_list(Fields) ->
    [];
as_maps(Fields, [])
    when is_list(Fields) ->
    [];
as_maps(Fields, Rows)
    when is_list(Fields), is_list(Rows) ->
    [begin
         maps:from_list([{binary_to_atom(K,utf8), V} || {K, V} <- lists:zip(Fields, R)])
     end || R <- Rows].

**Comment by zuiderkwast** [comment]
No need for the undefined stuff. Fields and Rows from `{ok, Fields, Rows} = mysql:query(...)` are always lists and the number of columns is the same for every row as the fields. Here is my version (basically the same as @snailman 's)

```Erlang
as_maps(Fields, Rows) ->
    AtomFields = [binary_to_atom(Field, utf8) || Field <- Fields],
    [maps:from_list(lists:zip(AtomFields, Row)) || Row <- Rows].
```
