### ISSUE TITLE
Cannot connect to MySQL 5.7

### ISSUE THREAD

**Issue by turtleDeng** [mysql-otp/mysql-otp#71]
![wechatimg672](https://user-images.githubusercontent.com/1830077/27855854-a30c1692-619e-11e7-8d52-6ff63016d29a.jpeg)

**Comment by silviucpp** [comment]
Works pretty fine for me with mysql 5.7 so problem it's somewhere else, you need to come up with more information.

**Comment by zuiderkwast** [comment]
Is this the same problem as #72, solved by #75? If it is, good. If not, please re-open!
