### ISSUE TITLE
Question: Does connect timeout infinity works perfectly?

### ISSUE THREAD

**Issue by shobhitsingh** [mysql-otp/mysql-otp#74]
I have couple of questions regarding the connect timeout value of infinity.

1) Will the infinity timeout works even if there is no query request for a long time?
2) I have saved the Pid returned by start_link() at the start of the service which is passed to Erlang processes when a request is received. When the MySQL node goes down, and then I restart the MySQL node, the connector will not work without restarting my service, thereby getting a new Pid. How to deal with such a case using the connector without restarting my service?

Thanks.

**Comment by zuiderkwast** [comment]
The coonect timeout is the time limit for connecting only. Maybe you are interested in the `keep_alive` option? To send pings to the server at certain intervals when the connection is unused for a long time.

**Comment by zuiderkwast** [comment]
For the second question, when your server goes down you need to reconnect. A new connection is implemented as a process, so the connection process has to be restarted. You don't have to restart your whole application. You can have a supervisor taking care of the MySQL connection(s) to handle this case. Maybe you also want to add some delay before re-connecting to make sure the server has had time to restart? That can not be done with a standard OTP supervisor though. It would need something like a custom gen_server for that.

I'm closing this issue. Please re-open if you don't feel that your questions have been well answered.
