### ISSUE TITLE
CHAR/VARCHAR vs BINARY/VARBINARY

### ISSUE THREAD

**Issue by adrianboston** [mysql-otp/mysql-otp#81]
Is there a method to accurately distinguish between a `CHAR/VARCHAR` and a `BINARY/VARBINARY` column.

A `BINARY` column in mysql is often defined as `TYPE_STRING` within mysql-otp (debugging msql_protocol.erl) while `VARBINARY` is often defined as `TYPE_VAR_STRING`.

The `type` seems to be determined from the element following the `column` name as shown where the `253` matches to `TYPE_VAR_STRING`.

ColDef={col,<<"columnname">>,**253**,33,150,0,0};

IMPORTANT:
Is the element following the `type` some sort of `sub-type.` As seen, `33` shows up for `CHAR/VARCHAR` while `63` for `BINARY/VARBINARY` columns.
Can anyone confirm this sub-type??

`CHAR, VARCHAR` and `TEXT` appear to be consistently `33`; while **all** others are `63`.

Data types according to protocol.hrl

%% --- Types ---

-define(TYPE_DECIMAL, 16#00).
-define(TYPE_TINY, 16#01).
-define(TYPE_SHORT, 16#02).
-define(TYPE_LONG, 16#03).
-define(TYPE_FLOAT, 16#04).
-define(TYPE_DOUBLE, 16#05).
-define(TYPE_NULL, 16#06).
-define(TYPE_TIMESTAMP, 16#07).
-define(TYPE_LONGLONG, 16#08).
-define(TYPE_INT24, 16#09).
-define(TYPE_DATE, 16#0a).
-define(TYPE_TIME, 16#0b).
-define(TYPE_DATETIME, 16#0c).
-define(TYPE_YEAR, 16#0d).
-define(TYPE_VARCHAR, 16#0f).
-define(TYPE_BIT, 16#10).
-define(TYPE_JSON, 16#f5).
-define(TYPE_NEWDECIMAL, 16#f6).
-define(TYPE_ENUM, 16#f7).
-define(TYPE_SET, 16#f8).
-define(TYPE_TINY_BLOB, 16#f9).
-define(TYPE_MEDIUM_BLOB, 16#fa).
-define(TYPE_LONG_BLOB, 16#fb).
-define(TYPE_BLOB, 16#fc).
-define(TYPE_VAR_STRING, 16#fd).
-define(TYPE_STRING, 16#fe).
-define(TYPE_GEOMETRY, 16#ff).

**Comment by zuiderkwast** [comment]
Interesting!

The value after `type` in the `col` record is the *character set*, where 33 = UTF-8; 63 = binary. The charset is stored in the col record but it is not used for anything. I guess it can only be UTF-8 or binary as long as we are using UTF-8 for the connection encoding.

Column definition in the prococol documentation:
https://dev.mysql.com/doc/internals/en/com-query-response.html#column-definition
https://dev.mysql.com/doc/internals/en/character-set.html#packet-Protocol::CharacterSet

The column definition is parsed here:
https://github.com/mysql-otp/mysql-otp/blob/9724d67a262b26ed9f325f8e9e17a5d1fc42e63b/src/mysql_protocol.erl#L493

Assuming it is possible to distinguish between binary and test, how do you suggest we should return it to the user of the library?

**Comment by adrianboston** [comment]
@zuiderkwast thank you. 

a.
Perhaps these defined types used throughout could be picking up both the `type` and `character set` such that one can accurately distinguish the binary.

-define(TYPE_STRING, {16#fe, 33}).
-define(TYPE_BINARY, {16#fe, 63}).

b.
Return the CHAR as an erlang string "" and BINARY as a binary string <<"">> or <<[]>>
OR
Return the binary in base 64 ?!

Note that one problem is pattern matching <<"A character string">> and a <<137,80,78, ...                 14,192,32,8,4,7,211,255,127,121,123,209,214,82,17,149,196>>
Both end up matching is_binary especially difficult if the size is not known.

What i do is return the type in the result set from `decode_text_row_acc/3`. Note that this doesn't help the confusion between `CHAR` and `BINARY` but does help avoid a type match in the users code.

```
{ok,[<<"id">>,<<"col1">>,<<"col2">>,<<"col3">> ...<<"colX">>],
    [[{string,<<4,63,74,120,236,81,17,231,136,148,172,188,50,143,101,43>>},
      {varstring,<<"">>},
      {short,99},
      {string,<<215,77,116,215,77,116,0,0,0,0,0,0,0,0,0,0>>},
      null,null,
      {bit,<<1:1>>},
      {varstring,<<137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,15,0,0,
                   0,16,8,6,0,0,0,201,86,37,4,0,0,0,4,103,65,77,65,0,1,134,
                  ...
                   96,97,159,40,209,178,188,147,145,179,25,209,63,21,33,185,
                   78,68,174,66,96,130>>},
      {string,<<176,58,251,128,199,67,17,230,157,157,206,192,201,50,206,1>>},
      {string,<<187,31,47,238,199,67,17,230,157,157,206,192,201,50,206,1>>},
      {tiny,4},
      {timestamp,{{2017,12,28},{20,30,36}}},
      {tiny,1}]]}


```

**Comment by adrianboston** [comment]
It seems there are many binary collations so the accuracy of `63` may not work.

https://dev.mysql.com/doc/internals/en/charsets.html

...
65 | ascii | ascii_bin
63 | binary | binary
47 | latin1 | latin1_bin
...

Q: do you know whether a binary collation (`latin1_bin`?) **would be/can be** used for say a `BINARY,VARBINARY` column in .. `latin1`

**Comment by adrianboston** [comment]
Collation is only applied to CHAR, VARCHAR, or TEXT, according to mysql docs.

In other words, `63` seems to be consistent for BINARY/VARBINARY (and INTS, etc), while the `33` is not consistent for any of those 3 columns. Which suggests it is possible to determine the difference.

say,
```
-define(TYPE_BINARY, {16#fe, 63}).
-define(TYPE_STRING, {16#fe, _}).

```

**Comment by adrianboston** [comment]
Agreed that binaries is more efficient. So a function for making queries is probably the best solution; as well for backward comp. 
I do base 64 on any `BLOB` or `BINARY` column and don't on `CHAR`, etc

**Comment by zuiderkwast** [comment]
I don't consider this important, so I'm closing the issue. Feel free to discuss it further if you want.
