### ISSUE TITLE
1.3.2 Hex package

### ISSUE THREAD

**Issue by michalwski** [mysql-otp/mysql-otp#82]
Is there any change for the hex page for version 1.3.2? Currently the newest hex package is 1.3.1

**Comment by michalwski** [comment]
@tjheeta can I help you somehow to get the 1.3.2 version in hex?

**Comment by GeraldXv** [comment]
@tjheeta can you add support hex.pm support with rebar3.config?

**Comment by getong** [comment]
Now it is 1.3.3

**Comment by michaellenaghan** [comment]
I think the "it" in "Now it is 1.3.3" refers to the current version of mysql-otp rather than the [what's in Hex](https://hex.pm/packages/mysql); that's still 1.3.1.

**Comment by zuiderkwast** [comment]
I know. The problem is that I'm not responsible for this project in Hex. Can I be made an administrator in Hex?

**Comment by getong** [comment]
Yes, you can do according to:
https://hex.pm/policies/dispute#if-you-wish-to-acquire-an-existing-package-name

**Comment by michaellenaghan** [comment]
I think this can be closed now: https://hex.pm/packages/mysql

**Comment by zuiderkwast** [comment]
Sure. We should make it a habit updating it with every new version, but that's a different topic.

@GeraldXv You can use rebar3 with the hex package, even if there is no rebar config file, can't you? No rebar configuration is needed AFAIK.
