### ISSUE TITLE
Can we add a stop method ?

### ISSUE THREAD

**Issue by silviucpp** [mysql-otp/mysql-otp#87]
Hello I think will be useful to have a stop method that stops the connection gen_server gracefully without any noise. Right now the only way is exit(Pid, kill) which creates lot of noise

Silviu

**Comment by zuiderkwast** [comment]
Hi! It's a good question.

The proper way to stop a gen_server (when it is not in a supervision tree) should be [gen_server:stop/1,3](http://erlang.org/doc/man/gen_server.html#stop-1), right? We can add a stop function as a wrapper for gen_server:stop if you think it would be useful.

However, primarily it is designed to be included in a supervision tree so it is designed to be stopped in the way a supervisor stops its children. I've always wondered why supervisors don't have a stop function and why there is not a stop function that it is calling on the children to stop them. I guess the answer is simply that `kill` is used for these tasks.

Here are the docs for [supervisor](http://erlang.org/doc/man/supervisor.html) about the shutdown parameter in a child spec:

> shutdown defines how a child process must be terminated. brutal_kill means that the child process is unconditionally terminated using exit(Child,kill). An integer time-out value means that the supervisor tells the child process to terminate by calling exit(Child,shutdown) and then wait for an exit signal with reason shutdown back from the child process. If no exit signal is received within the specified number of milliseconds, the child process is unconditionally terminated using exit(Child,kill).

It should be possible to stop it with `kill(Pid, shutdown)` without noise. Is it not? If not, this needs to be fixed.

**Comment by silviucpp** [comment]
I tested with reason shutdown but I don't see the processes being closed.. Only with kill I see them gone.

Other projects are using a stop message:

https://github.com/wooga/eredis/blob/master/src/eredis_client.erl#L65

and basically when it's received it stopping the gen_server:

https://github.com/wooga/eredis/blob/master/src/eredis_client.erl#L96

Silviu

**Comment by zuiderkwast** [comment]
I see. But this doesn't solve the scenario when you want to stop a supervisor which contains a mysql connection.

For exit(Pid, shutdown) to work, I think we need to trap exits (see docs for [exit/2](http://erlang.org/doc/man/erlang.html#exit-2)). This is already done. The gen_server itself catches the exit signal from it's parent (the process that started the gen_server) and I thought it should handle it and call terminate... I don't know why it is not happening right now..

If we fix this, which I think we should, we can also implement the a stop function using exit(Pid, normal).

**Comment by zuiderkwast** [comment]
Tested this manually today in an Erlang shell. It works in this way:

* `exit(Pid, normal).` stops the connection without noise.
* `exit(Pid, shutdown).` causes an exit signal which if `trap_exit` is activated is turned into a message `{'EXIT',<0.95.0>,shutdown}` to the calling process.
* `exit(Pid, kill).` causes an exit signal or a message `{'EXIT',<0.103.0>,killed}`.
* `exit(Pid, banana).` (or some other non-standard value) causes an exit signal or message `{'EXIT',<0.110.0>,banana}` and additionally an error report on the form below. (This is on OTP 19.) 

```
=ERROR REPORT==== 20-Nov-2018::22:36:57 ===
** Generic server <0.110.0> terminating 
** Last message in was {'EXIT',<0.90.0>,banana}
** When Server state == {state,[5,6,30],
                               13,#Port<0.657>,mysql_sock_tcp,undefined,
                               "localhost",3306,"otptest","otptest",true,
                               infinity,infinity,60000,0,2,0,0,0,undefined,
                               {dict,0,16,16,8,80,48,
                                     {[],[],[],[],[],[],[],[],[],[],[],[],[],
                                      [],[],[]},
                                     {{[],[],[],[],[],[],[],[],[],[],[],[],[],
                                       [],[],[]}}},
                               empty,false}
** Reason for termination == 
** banana
```

----

I would like to close this issue when these actions are taken:

* Add `exit(Pid, normal)` to the README examples
* Check if there is a test case and add one otherwise
