### ISSUE TITLE
Can't connect to MariaDB 10.1.21

### ISSUE THREAD

**Issue by pdorofiejczyk** [mysql-otp/mysql-otp#88]
OTP: 20
MariaDB: 10.1.21
mysql-opt: 1.3.2

Getting error:

`{unknown_protocol,[{mysql_protocol,parse_handshake,1,[{file,"src/mysql_protocol.erl"},{line,245}]},{mysql_protocol,handshake,7,[{file,"src/mysql_protocol.erl"},{line,60}]},{mysql,init,1,[{file,"src/mysql.erl"},{line,499}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}`

**Comment by zuiderkwast** [comment]
Thank's for the report! Solutions and clues are much appreciated!

**Comment by zuiderkwast** [comment]
The server sends an error packet (Too many connections) as the first package. This seems to be a bug in this specific version (10.1.21) of MariaDB. I tested with 10.1.37 and it doesn't seem to have this behaviour. According to https://mariadb.com/kb/en/library/connection/, the server is always supposed to send an Initial Handshake packet as the first packet. The "Too many connections" error should come in the next step. See also the commit message for the fix.
